import { createHash } from 'node:crypto';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import { registerTool, type CallerHashProvider, type ToolResultPayload } from '../registry.js';
import type { CloudBrowserAction } from '../browser-cloud/index.js';
import { CloudBrowserJobs, type CloudBrowserArtifactStore, type CloudBrowserWorkerQueue } from '../browser-cloud-jobs/contracts.js';
import { CloudBrowserJobWorker, type CloudBrowserPlanExecutor } from '../browser-cloud-jobs/worker.js';

const actionSchema = z.discriminatedUnion('type', [z.object({ type: z.literal('navigate'), url: z.string().url().max(2048) }), z.object({ type: z.literal('click'), selector: z.string().min(1).max(256) }), z.object({ type: z.literal('type'), selector: z.string().min(1).max(256), text: z.string().min(1).max(1024) }), z.object({ type: z.literal('wait_for'), selector: z.string().min(1).max(256) })]);
const planSchema = z.object({ profile_id: z.string().regex(/^[A-Za-z0-9_-]{3,64}$/), max_seconds: z.number().int().min(1).max(300), actions: z.array(z.discriminatedUnion('type', [z.object({ type: z.literal('navigate'), url: z.string().url().max(2048) }), z.object({ type: z.literal('wait_for'), selector: z.string().min(1).max(256) })])).min(1).max(20) }).strict();
type DeterministicPlan = z.infer<typeof planSchema>;

export function redactCloudBrowserInputForLog(input: Record<string, unknown>): unknown {
  const copy = { ...input };
  if (copy.action !== undefined) copy.action = '[redacted browser action]';
  if (copy.plan !== undefined) copy.plan = '[redacted browser plan]';
  if (copy.text !== undefined || copy.url !== undefined || copy.selector !== undefined) return { operation: 'browser_cloud', input: '[redacted browser input]' };
  return copy;
}
/** Shield scans may inspect operation metadata only. Typed text, URLs and selectors are never sent. */
export function shieldCloudBrowserInput(input: Record<string, unknown>): unknown { return { operation: 'browser_cloud', fields: Object.keys(input).filter(key => !['action', 'plan', 'text', 'url', 'selector'].includes(key)).sort() }; }
export function validateDeterministicPlan(value: unknown): DeterministicPlan { return planSchema.parse(value); }
export function cloudBrowserRuntimeStatus(): { enabled: boolean; reason?: string } { return process.env.CLOUD_BROWSER_ENABLED === 'true' && !!process.env.CLOUD_BROWSER_DDB_TABLE && !!process.env.CLOUD_BROWSER_QUEUE_URL && !!process.env.CLOUD_BROWSER_ARTIFACT_BUCKET ? { enabled: true } : { enabled: false, reason: 'Cloud browser is disabled or its durable DynamoDB table, SQS queue, and S3 artifact bucket are not configured.' }; }
function unavailable(): ToolResultPayload { const state = cloudBrowserRuntimeStatus(); return { data: { error: 'cloud_browser_not_configured' }, summary: state.reason ?? 'Cloud browser runtime is unavailable.' }; }
function error(error: unknown): ToolResultPayload { const code = error && typeof error === 'object' && typeof (error as { code?: unknown }).code === 'string' ? (error as { code: string }).code : 'cloud_browser_failed'; return { data: { error: code }, summary: `Cloud browser request was not completed: ${code}.` }; }

/** `snapshot` is intentionally metadata-only and is supplied by the session-core owner. */
export interface CloudBrowserGatewayService {
  start(caller: string, profileId: string, maxSeconds: number): Promise<{ sessionId: string; expiresAt: number }>;
  execute(caller: string, sessionId: string, action: CloudBrowserAction, timeoutSeconds: number): Promise<unknown>;
  stop(caller: string, sessionId: string): Promise<void>;
  savePersistentProfile(caller: string, sessionId: string): Promise<void>;
  snapshot(caller: string, sessionId: string): Promise<unknown>;
}
export interface CloudBrowserGatewayRuntime { browser: CloudBrowserGatewayService; jobs: CloudBrowserJobs; queue: CloudBrowserWorkerQueue; artifacts: CloudBrowserArtifactStore; }
/** Register narrow MCP tools. Owner identity always comes from ToolContext.callerAgent. */
export function registerCloudBrowserTools(server: McpServer, callerHash: CallerHashProvider, runtime: CloudBrowserGatewayRuntime): void {
  const live = () => cloudBrowserRuntimeStatus().enabled;
  registerTool(server, { name: 'browser_cloud_job_submit', category: 'write_simple', annotations: { title: 'Cloud browser: submit bounded job', description: 'Persists a deterministic read-only cloud browser plan. Owner identity is the authenticated caller.', readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: true }, inputShape: { idempotency_key: z.string().min(8).max(255), plan: z.unknown() }, outputShape: { job_id: z.string().optional(), replayed: z.boolean().optional(), error: z.string().optional() }, redactInputForLog: redactCloudBrowserInputForLog, shieldInputForScan: shieldCloudBrowserInput, handler: async (input, ctx) => { if (!live()) return unavailable(); if (ctx.dryRun) { validateDeterministicPlan(input.plan); return { data: { dry_run: true }, summary: 'Validated deterministic plan. No job was created.' }; } try { const out = await runtime.jobs.submit({ agent: ctx.callerAgent, idempotencyKey: input.idempotency_key, request: validateDeterministicPlan(input.plan) }); return { data: { job_id: out.job.id, replayed: out.replayed, status: out.job.status }, summary: out.replayed ? 'Returned the existing durable browser job.' : 'Created a durable browser job.' }; } catch (e) { return error(e); } } }, callerHash);
  registerTool(server, { name: 'browser_cloud_job_get', category: 'read', annotations: { title: 'Cloud browser: get job', description: 'Reads an authenticated caller’s durable browser job without request text.', readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false }, inputShape: { job_id: z.string().max(128) }, outputShape: { job: z.unknown().optional(), error: z.string().optional() }, handler: async (input, ctx) => { if (!live()) return unavailable(); try { const job = await runtime.jobs.get(input.job_id, ctx.callerAgent); const { request: _request, ...safe } = job; return { data: { job: safe }, summary: `Browser job ${job.id} is ${job.status}.` }; } catch (e) { return error(e); } } }, callerHash);
  registerTool(server, { name: 'browser_cloud_artifact_get', category: 'read', annotations: { title: 'Cloud browser: get job artifact', description: 'Reads one bounded immutable artifact recorded on the authenticated caller’s job.', readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false }, inputShape: { job_id: z.string().max(128), artifact_id: z.string().max(128) }, outputShape: { artifact: z.unknown().optional(), error: z.string().optional() }, handler: async (input, ctx) => { if (!live()) return unavailable(); try { const job = await runtime.jobs.get(input.job_id, ctx.callerAgent); const artifact = job.artifacts.find(item => item.id === input.artifact_id); if (!artifact) return { data: { error: 'artifact_not_found' }, summary: 'Artifact is unavailable to this caller.' }; const value = await runtime.artifacts.getVersion({ key: artifact.storageKey, version: artifact.storageVersion, maxBytes: 1_000_000 }); const actual = createHash('sha256').update(value.body).digest('hex'); if (actual !== artifact.sha256) return { data: { error: 'artifact_integrity_failed' }, summary: 'Artifact integrity validation failed.' }; return { data: { artifact: { id: artifact.id, content_type: value.contentType, text: value.body.toString('utf8') } }, summary: 'Immutable job artifact returned.' }; } catch (e) { return error(e); } } }, callerHash);
  registerTool(server, { name: 'browser_cloud_job_cancel', category: 'write_simple', annotations: { title: 'Cloud browser: cancel job', description: 'Requests cancellation of the authenticated caller’s queued or running job.', readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false }, inputShape: { job_id: z.string().max(128) }, outputShape: { status: z.string().optional(), error: z.string().optional() }, handler: async (input, ctx) => { if (!live()) return unavailable(); if (ctx.dryRun) return { data: { dry_run: true }, summary: 'Cancellation was not requested.' }; try { const job = await runtime.jobs.requestCancellation(input.job_id, ctx.callerAgent); return { data: { status: job.status }, summary: 'Cancellation state was saved.' }; } catch (e) { return error(e); } } }, callerHash);
  registerTool(server, { name: 'browser_cloud_session_start', category: 'write_simple', annotations: { title: 'Cloud browser: start session', description: 'Starts an authenticated caller’s bounded cloud browser session.', readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true }, inputShape: { profile_id: z.string().max(64), max_seconds: z.number().int().min(1).max(180) }, outputShape: { sessionId: z.string().optional(), expiresAt: z.number().optional(), error: z.string().optional() }, handler: async (input, ctx) => { if (!live()) return unavailable(); if (ctx.dryRun) return { data: { dry_run: true }, summary: 'Session start was not executed.' }; try { return { data: await runtime.browser.start(ctx.callerAgent, input.profile_id, input.max_seconds), summary: 'Cloud browser session started.' }; } catch (e) { return error(e); } } }, callerHash);
  registerTool(server, { name: 'browser_cloud_session_action', category: 'write_simple', annotations: { title: 'Cloud browser: bounded session action', description: 'Executes one bounded browser action. It accepts no arbitrary JavaScript.', readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true }, inputShape: { session_id: z.string().max(128), action: actionSchema, timeout_seconds: z.number().int().min(1).max(20) }, outputShape: { ok: z.boolean().optional(), error: z.string().optional() }, redactInputForLog: redactCloudBrowserInputForLog, shieldInputForScan: shieldCloudBrowserInput, handler: async (input, ctx) => { if (!live()) return unavailable(); if (ctx.dryRun) return { data: { dry_run: true }, summary: 'Browser action was not executed.' }; try { await runtime.browser.execute(ctx.callerAgent, input.session_id, input.action as CloudBrowserAction, input.timeout_seconds); return { data: { ok: true }, summary: 'Bounded browser action completed.' }; } catch (e) { return error(e); } } }, callerHash);
  for (const [name, method, title] of [['browser_cloud_session_snapshot', 'snapshot', 'Cloud browser: session snapshot'], ['browser_cloud_profile_save', 'save', 'Cloud browser: save persistent profile'], ['browser_cloud_session_stop', 'stop', 'Cloud browser: stop session']] as const) registerTool(server, { name, category: method === 'snapshot' ? 'read' : 'write_simple', annotations: { title, description: method === 'snapshot' ? 'Returns a bounded page observation for the authenticated session.' : 'Performs a bounded cloud browser lifecycle operation.', readOnlyHint: method === 'snapshot', destructiveHint: false, idempotentHint: method !== 'save', openWorldHint: false }, inputShape: { session_id: z.string().max(128) }, outputShape: { ok: z.boolean().optional(), session: z.unknown().optional(), error: z.string().optional() }, handler: async (input, ctx) => { if (!live()) return unavailable(); try { if (method === 'snapshot') { const session = await runtime.browser.snapshot(ctx.callerAgent, input.session_id); return { data: { session }, summary: 'Bounded cloud browser page observation returned.' }; } if (ctx.dryRun) return { data: { dry_run: true }, summary: 'Lifecycle action was not executed.' }; if (method === 'save') await runtime.browser.savePersistentProfile(ctx.callerAgent, input.session_id); else await runtime.browser.stop(ctx.callerAgent, input.session_id); return { data: { ok: true }, summary: 'Cloud browser lifecycle action completed.' }; } catch (e) { return error(e); } } }, callerHash);
}

export function startCloudBrowserWorker(runtime: CloudBrowserGatewayRuntime): CloudBrowserJobWorker | null {
  if (!cloudBrowserRuntimeStatus().enabled) return null;
  const executor: CloudBrowserPlanExecutor = { execute: async (job, control) => { const plan = validateDeterministicPlan(job.request); const started = await runtime.browser.start(job.agent, plan.profile_id, plan.max_seconds); try { for (let index = 0; index < plan.actions.length; index++) { if (control.cancellationRequested()) return; const action = plan.actions[index]!; const step = `action:${index}`; if (await control.heartbeat()) return; await control.beginExternalEffect(step); await runtime.browser.execute(job.agent, started.sessionId, action, 20); await runtime.jobs.recordExternalEffectSucceeded(job.id, job.agent, job.leaseToken, step); } const observation = await runtime.browser.snapshot(job.agent, started.sessionId); const body = Buffer.from(JSON.stringify(observation)); await runtime.jobs.attachArtifact(job.id, job.agent, job.leaseToken, body, 'application/json', createHash('sha256').update(body).digest('hex')); return observation; } finally { await runtime.browser.stop(job.agent, started.sessionId); } } };
  return new CloudBrowserJobWorker(runtime.jobs, runtime.queue, executor);
}
