import assert from 'node:assert/strict';
import test from 'node:test';
import Fastify from 'fastify';
Object.assign(process.env,{CIO_SITE_ID:'synthetic',CIO_TRACK_KEY:'synthetic',CIO_APP_API_BEARER:'synthetic',PERPLEXITY_CONNECTOR_TOKEN:'synthetic-fixture-only-not-real-000001',ADMIN_REVOKE_TOKEN:'synthetic-fixture-only-not-real-000002',N8N_WEBHOOK_SECRET:'synthetic-fixture-only-not-real-000003'});
const {registerGraphCatalogControllerRoutes,resolveCatalogCohortBinding,graphCatalogControllerTest:internals}=await import('./graph-catalog-controller.js');
import { planGraphCatalogPage } from './graph-catalog-planner.js';
import { verifyMaterializationReceipt } from './materialized-catalog-pin.js';
const {canonical,hash}=internals;
const ctx={caller_agent:'cfo',caller_hash:'synthetic',raw_token:'synthetic-fixture',connector_surface:true,m365_static_auth:false} as any;
async function harness(){
 const objects=new Map<string,{body:Buffer;etag:string}>();let revision=0,calls=0,failActivation=false,now=Date.now();
 const cfg={cohort_id:'synthetic',catalog_key:'graph-trial/synthetic/catalog.jsonl',catalog_source_sha256:hash('synthetic catalog'),source_prefixes:['synthetic/'],purpose:'company_graph_backfill',run_version:'test-v1',batch_size:2,max_admissions:2,policy_sha256:hash('synthetic policy'),expires_at:new Date(now+3600000).toISOString(),recovery_policy_sha256:hash('synthetic recovery'),recovery_expires_at:new Date(now+7200000).toISOString()};
 let configs:any[]=[cfg];const rows=['a','b','c'].map(x=>({path:`synthetic/${x}.txt`,sha256:hash(x),sidecar:true,enriched:true,enriched_sha256:hash(x),entity:'Synthetic'}));
 const text=rows.map(canonical).join('\n')+'\n',createdAt='2026-09-08T00:00:00.000Z';
 const catalog={rows,catalogEtag:'"catalog-v1"',catalogSourceSha256:cfg.catalog_source_sha256,createdAt};
 const deps={configs:()=>canonical(configs),now:()=>now,authenticate:async(r:any)=>({...ctx,caller_agent:r.headers.authorization==='Bearer synthetic-cfo-token'?'cfo':'cto'}),
  catalogS3:async(r:any)=>{calls++;assert.equal(r.key,cfg.catalog_key);if(r.method==='GET')assert.equal(r.headers['if-match'],catalog.catalogEtag);return{status:200,headers:new Headers({etag:catalog.catalogEtag,'content-length':String(Buffer.byteLength(text)),'last-modified':createdAt}),body:r.method==='HEAD'?null:new Response(text).body};},
  s3:async(r:any)=>{calls++;const old=objects.get(r.key);if(r.method==='GET')return{status:old?200:404,headers:new Headers(old?{etag:old.etag}:{}),body:old?.body??Buffer.alloc(0)};
   const heads=new Headers(r.headers);if(heads.get('if-none-match')==='*'&&old||heads.has('if-match')&&heads.get('if-match')!==old?.etag)return{status:412,headers:new Headers(),body:Buffer.alloc(0)};
   if(failActivation&&r.key.endsWith('/server/control.json')&&(JSON.parse(r.body.toString()).active??[JSON.parse(r.body.toString()).current]).some((v:any)=>v?.status==='active')){failActivation=false;return{status:503,headers:new Headers(),body:Buffer.alloc(0)};}
   const saved={body:Buffer.from(r.body),etag:`"${++revision}"`};objects.set(r.key,saved);return{status:200,headers:new Headers({etag:saved.etag}),body:Buffer.alloc(0)};
  }};
 const app=Fastify({logger:false});registerGraphCatalogControllerRoutes(app,deps);
 const request=async(path:string,value?:unknown,method?:string,token='synthetic-cfo-token')=>app.inject({method:(method??(value===undefined?'GET':'POST')) as any,url:'/graph-catalog/v1/synthetic'+path,headers:{authorization:'Bearer '+token,'content-type':'application/json'},...(value===undefined?{}:{payload:JSON.stringify(value)})});
 const publish=async(n=0)=>{const page=planGraphCatalogPage({...catalog,rows:[rows[n]],limit:1}).page;const r=await request('/publish',{manifest:page.manifest,rows:page.rows});assert.equal(r.statusCode,200,r.body);return internals.proposal(cfg,catalog,page.manifest);};
 return{app,deps,cfg,catalog,objects,request,publish,get calls(){return calls;},setConfigs:(v:any[])=>{configs=v;},failActivation:()=>{failActivation=true;},expire:()=>{now+=3600001;}};
}
test('default registration is offline and absent or malformed cohorts never read S3',async()=>{const app=Fastify();assert.doesNotThrow(()=>registerGraphCatalogControllerRoutes(app));await app.close();const h=await harness();try{h.setConfigs([]);assert.equal((await h.request('/config')).statusCode,404);assert.equal(h.calls,0);h.setConfigs([{...h.cfg,source_prefixes:['../']}]);assert.equal((await h.request('/config')).statusCode,404);assert.equal(h.calls,0);h.setConfigs([h.cfg]);assert.equal((await h.request('/page',{cursor:null,limit:1},'POST','synthetic-cto-token')).statusCode,403);assert.equal(h.calls,0);}finally{await h.app.close();}});
test('target page returns only the requested immutable source and never changes cursor state',async()=>{const h=await harness();try{const page=planGraphCatalogPage({...h.catalog,rows:[h.catalog.rows[1]],limit:1}).page,doc=page.manifest!.documents[0];const r=await h.request('/target-page',{source_document_version:doc.document_version_id,catalog_source_sha256:doc.source_version});assert.equal(r.statusCode,200,r.body);assert.deepEqual(r.json().page.manifest,page.manifest);assert.equal(r.json().page.next_cursor,null);assert.equal((await h.request('/state/cursor')).statusCode,404);assert.equal((await h.request('/target-page',{source_document_version:doc.document_version_id,catalog_source_sha256:'0'.repeat(64)})).statusCode,409);}finally{await h.app.close();}});
test('target proposal gives an existing source a distinct promotion run, then admits without cursor state',async()=>{const h=await harness();try{const ordinary=await h.publish(1),item=ordinary.manifest.documents[0];const r=await h.request('/target-proposal',{source_document_version:item.document_version_id,catalog_source_sha256:item.source_version});assert.equal(r.statusCode,200,r.body);const target=r.json().proposal;assert.notEqual(target.key,ordinary.key);assert.notEqual(target.run.run_id,ordinary.run.run_id);assert.equal(target.manifest.manifest_sha256,ordinary.manifest.manifest_sha256);assert.equal((await h.request('/state/cursor')).statusCode,404);
 const key=`versions/${target.key}`,prepared={schema:'catalog-controller-version-v1',proposal:target,status:'prepared',outcome:null,chunks:[],preparation:null};assert.equal((await h.request('/state/'+key,{key,revision:null,value:prepared},'PUT')).statusCode,200);assert.deepEqual((await h.request('/manifests/'+target.manifest.manifest_sha256,undefined,'GET')).json(),target.manifest);const admission=await h.request('/admit',{key:target.key,manifest_sha256:target.manifest.manifest_sha256});assert.equal(admission.statusCode,200,admission.body);assert.equal(admission.json().run_id,target.run.run_id);assert.equal((await h.request('/state/cursor')).statusCode,404);assert.equal((await h.request('/target-proposal',{source_document_version:item.document_version_id,catalog_source_sha256:'0'.repeat(64)})).statusCode,409);
 }finally{await h.app.close();}});
test('promotion completion binds an immutable publication and lineage without extractor receipts while another admission remains active',async()=>{const h=await harness();try{h.setConfigs([{...h.cfg,max_admissions:3,max_active_admissions:2}]);const parent=await h.publish(0),item=parent.manifest.documents[0],targetReply=await h.request('/target-proposal',{source_document_version:item.document_version_id,catalog_source_sha256:item.source_version}),target=targetReply.json().proposal,key=`versions/${target.key}`,prepared={schema:'catalog-controller-version-v1',proposal:target,status:'prepared',outcome:null,chunks:[],preparation:null};assert.equal((await h.request('/state/'+key,{key,revision:null,value:prepared},'PUT')).statusCode,200);assert.equal((await h.request('/admit',{key:target.key,manifest_sha256:target.manifest.manifest_sha256})).statusCode,200);const concurrent=await h.publish(1),concurrentAdmission=await h.request('/admit',{key:concurrent.key,manifest_sha256:concurrent.manifest.manifest_sha256});assert.equal(concurrentAdmission.statusCode,200,concurrentAdmission.body);assert.ok(await resolveCatalogCohortBinding(ctx,concurrent.run.run_id,AbortSignal.timeout(5000),h.deps));
 const artifact=(digest:string)=>({schema:'relationship-resolution-artifact-ref-v1',artifact_id:'resart_'+digest,bucket:'otchealth-finance-legal-dr-55c84f6b',key:`resolution-artifacts/sha256/${digest.slice(0,2)}/${digest}.json`,payload_sha256:digest,version_id:'synthetic-v1',size_bytes:1}),published=artifact('a'.repeat(64)),parentArtifact=artifact('b'.repeat(64)),source_refs=[{source_document_version:item.document_version_id,catalog_source_sha256:item.source_version,chunk_sha256:'c'.repeat(64)}],body={key:target.key,run_id:target.run.run_id,artifact_ref:published,producer_id:'cfo-relationship-worker',parent_run:parent.run,parent_artifact_ref:parentArtifact,source_refs,source_refs_sha256:hash(canonical(source_refs))},grant={schema:'relationship-publication-grant-v1',cohort_id:'synthetic',producer_id:'cfo-relationship-worker',caller_hash:'d'.repeat(64),run:target.run,admission:{synthetic:true},proposal:{synthetic:true},artifact_ref:published,approved_artifacts:[{digest:published.payload_sha256,version_id:published.version_id}],issued_under_policy_version:'synthetic-policy'};
 h.objects.set(`graph-trial/20260908/relationship-publications/cfo/synthetic/cfo-relationship-worker/runs/${target.run.run_id}.json`,{body:Buffer.from(canonical(grant)),etag:'"grant"'});assert.equal((await h.request('/promotion-complete',{...body,source_refs:[]})).statusCode,409);const completion=await h.request('/promotion-complete',body);assert.equal(completion.statusCode,200,completion.body);assert.equal((await h.request('/promotion-complete',body)).statusCode,200);assert.ok(await resolveCatalogCohortBinding(ctx,target.run.run_id,AbortSignal.timeout(5000),h.deps));assert.ok(await resolveCatalogCohortBinding(ctx,concurrent.run.run_id,AbortSignal.timeout(5000),h.deps));const next=await h.publish(2),admission=await h.request('/admit',{key:next.key,manifest_sha256:next.manifest.manifest_sha256});assert.equal(admission.statusCode,200,admission.body);assert.equal((await h.request('/state/cursor')).statusCode,404);
 }finally{await h.app.close();}});
test('immutable publication and ETag state reject forged proposals and authority paths',async()=>{const h=await harness();try{const p=await h.publish();const value={schema:'catalog-controller-version-v1',proposal:p,status:'prepared',outcome:null,chunks:[],preparation:null};const key=`versions/${p.key}`;
 assert.equal((await h.request('/state/server/control',{key:'server/control',revision:null,value},'PUT')).statusCode,400);
 assert.equal((await h.request('/state/'+key,{key,revision:null,value:{...value,proposal:{...p,max_documents:2}}},'PUT')).statusCode,400);
 const first=await h.request('/state/'+key,{key,revision:null,value},'PUT');assert.equal(first.statusCode,200,first.body);const revision=first.json().revision;
 const dispatched=await h.request('/state/'+key,{key,revision,value:{...value,status:'dispatching'}},'PUT');assert.equal(dispatched.statusCode,200,dispatched.body);
 assert.equal((await h.request('/state/'+key,{key,revision:dispatched.json().revision,value},'PUT')).statusCode,409);
 assert.equal((await h.request('/state/'+key,{key,revision:dispatched.json().revision,value:{...value,status:'complete'}},'PUT')).statusCode,400);
 }finally{await h.app.close();}});
test('v2 permits two active runs, exposes trusted capacity, and rejects a third with the named capacity denial',async()=>{const h=await harness();try{h.setConfigs([{...h.cfg,max_admissions:3,max_active_admissions:2}]);const config=await h.request('/config');assert.equal(config.statusCode,200,config.body);assert.equal(config.json().max_active_admissions,2);const first=await h.publish(0),second=await h.publish(1);for(const p of [first,second])assert.equal((await h.request('/admit',{key:p.key,manifest_sha256:p.manifest.manifest_sha256})).statusCode,200);const ctl=JSON.parse(h.objects.get(`${internals.BASE}/synthetic/server/control.json`)!.body.toString());assert.equal(ctl.schema,'graph-catalog-control-v2');assert.equal(ctl.used,2);assert.deepEqual(new Set(ctl.active.map((v:any)=>v.run_id)),new Set([first.run.run_id,second.run.run_id]));for(const p of [first,second]){assert.ok(await resolveCatalogCohortBinding(ctx,p.run.run_id,AbortSignal.timeout(5000),h.deps));assert.equal((await h.request('/review',{key:p.key,run_id:p.run.run_id,manifest_sha256:p.manifest.manifest_sha256})).statusCode,200);}const third=await h.publish(2),capacity=await h.request('/admit',{key:third.key,manifest_sha256:third.manifest.manifest_sha256});assert.equal(capacity.statusCode,409,capacity.body);assert.equal(capacity.json().error,'graph_catalog_active_capacity');}finally{await h.app.close();}});

test('legacy v1 control is preserved on read and migrates its reserved entry to v2 on exact admit',async()=>{const h=await harness();try{const p=await h.publish(0),legacy={schema:'graph-catalog-control-v1',policy_sha256:h.cfg.policy_sha256,used:1,current:{status:'reserved',key:p.key,run_id:p.run.run_id,manifest_sha256:p.manifest.manifest_sha256}};h.objects.set(`${internals.BASE}/synthetic/server/control.json`,{body:Buffer.from(canonical(legacy)),etag:'"legacy"'});const admission=await h.request('/admit',{key:p.key,manifest_sha256:p.manifest.manifest_sha256});assert.equal(admission.statusCode,200,admission.body);const migrated=JSON.parse(h.objects.get(`${internals.BASE}/synthetic/server/control.json`)!.body.toString());assert.equal(migrated.schema,'graph-catalog-control-v2');assert.equal(migrated.used,1);assert.deepEqual(migrated.active,[{...legacy.current,status:'active'}]);assert.ok(await resolveCatalogCohortBinding(ctx,p.run.run_id,AbortSignal.timeout(5000),h.deps));}finally{await h.app.close();}});
test('reservation consumes budget before authority and lost activation remains inactive until exact retry',async()=>{const h=await harness();try{const p=await h.publish();h.failActivation();const first=await h.request('/admit',{key:p.key,manifest_sha256:p.manifest.manifest_sha256});assert.equal(first.statusCode,503,first.body);
 assert.equal(await resolveCatalogCohortBinding(ctx,p.run.run_id,AbortSignal.timeout(5000),h.deps),null);
 const ctl=()=>JSON.parse(h.objects.get(`${internals.BASE}/synthetic/server/control.json`)!.body.toString());assert.equal(ctl().used,1);assert.equal(ctl().active[0].status,'reserved');
 const retried=await h.request('/admit',{key:p.key,manifest_sha256:p.manifest.manifest_sha256});assert.equal(retried.statusCode,200,retried.body);assert.equal(ctl().used,1);
 assert.ok(await resolveCatalogCohortBinding(ctx,p.run.run_id,AbortSignal.timeout(5000),h.deps));
 assert.deepEqual((await h.request('/admit',{key:p.key,manifest_sha256:p.manifest.manifest_sha256})).json(),retried.json());
 const next=await h.publish(1);assert.equal((await h.request('/admit',{key:next.key,manifest_sha256:next.manifest.manifest_sha256})).statusCode,409);assert.equal(ctl().used,1);
 h.expire();assert.equal(await resolveCatalogCohortBinding(ctx,p.run.run_id,AbortSignal.timeout(5000),h.deps),null);assert.equal((await h.request('/recovery',{key:p.key,run_id:p.run.run_id})).statusCode,200);assert.equal((await h.request('/page',{cursor:null,limit:1})).statusCode,403);
 }finally{await h.app.close();}});

test('scoped recovery resumes only a null-preparation active admission and repeat admit stays idempotent',async()=>{const h=await harness();try{const p=await h.publish(),key=`versions/${p.key}`,prepared={schema:'catalog-controller-version-v1',proposal:p,status:'prepared',outcome:null,chunks:[],preparation:null};
 const created=await h.request('/state/'+key,{key,revision:null,value:prepared},'PUT');assert.equal(created.statusCode,200,created.body);
 const admission=await h.request('/admit',{key:p.key,manifest_sha256:p.manifest.manifest_sha256});assert.equal(admission.statusCode,200,admission.body);
 const dispatching=await h.request('/state/'+key,{key,revision:created.json().revision,value:{...prepared,status:'dispatching'}},'PUT');assert.equal(dispatching.statusCode,200,dispatching.body);
 const resumed=await h.request('/state/'+key,{key,revision:dispatching.json().revision,value:prepared},'PUT');assert.equal(resumed.statusCode,200,resumed.body);
 assert.deepEqual((await h.request('/admit',{key:p.key,manifest_sha256:p.manifest.manifest_sha256})).json(),admission.json());
 const dispatchedAgain=await h.request('/state/'+key,{key,revision:resumed.json().revision,value:{...prepared,status:'dispatching'}},'PUT');assert.equal(dispatchedAgain.statusCode,200,dispatchedAgain.body);
 const {recovery_policy_sha256,recovery_expires_at,...withoutRecovery}=h.cfg;h.setConfigs([withoutRecovery]);
 assert.equal((await h.request('/state/'+key,{key,revision:dispatchedAgain.json().revision,value:prepared},'PUT')).statusCode,409);
 }finally{await h.app.close();}});

test('source-evidence retry clears one Luna chunk only for terminal validation failure without a result',async()=>{
 async function attempt(operationState:string,outcomeCode:string,resultPresent:'valid'|'malformed'|null=null,model='gpt-5.6-luna',bundle='eb8df7c6174117aee526be567279ad005e38a21dfef5b577657390e2b0dd753e',extractorVersion='codex-subscription-extractor-v1'){const h=await harness();try{const p=await h.publish(),key=`versions/${p.key}`;assert.equal((await h.request('/admit',{key:p.key,manifest_sha256:p.manifest.manifest_sha256})).statusCode,200);
  const chunkSha=hash('prepared chunk'),sidecarSha=hash('sidecar'),identity={schema:'cfo-text-preparation-v1',run_id:p.run.run_id,document_ordinal:0,descriptor:{source_document_version:p.manifest.documents[0].document_version_id,sidecar_content_sha256:sidecarSha},chunks:[{ordinal:0,text_sha256:chunkSha}]},snapshotId=`txtsnap_${hash(canonical(identity))}`;
  const manifestContent={schema:'cfo-text-prepared-manifest-v1',snapshot_id:snapshotId,identity,bundles:[],chunks:[{ordinal:0,text_sha256:chunkSha}]},manifest={...manifestContent,manifest_sha256:hash(canonical(manifestContent))};
  h.objects.set(`graph-trial/20260908/workers/cfo/${p.run.run_id}/text-snapshots/${snapshotId}/manifest.json`,{body:Buffer.from(canonical(manifest)),etag:'"manifest"'});
  const binding={schema:'cfo-prepared-chunk-binding-v1',run_id:p.run.run_id,room:'finance',source_index:'finance-cfo-source-docs',catalog_manifest_sha256:p.run.manifest_sha256,document_ordinal:0,source_document_version:p.manifest.documents[0].document_version_id,catalog_source_sha256:p.manifest.documents[0].source_version,snapshot_id:snapshotId,prepared_manifest_sha256:manifest.manifest_sha256,sidecar_content_sha256:sidecarSha,chunk_ordinal:0,chunk_sha256:chunkSha};
  const spec={provider:'codex-chatgpt-subscription',model,extractor_version:extractorVersion,extractor_bundle_sha256:bundle,purpose:p.run.purpose,source_binding:binding},operationId=`subop_${hash(canonical(spec))}`,operation={operation_id:operationId,spec,state:operationState,claim_token:'synthetic-claim-token',revision:2,outcome_code:outcomeCode};
  h.objects.set(`graph-trial/20260908/workers/cfo/${p.run.run_id}/subscription-jobs/operations/${operationId}.json`,{body:Buffer.from(canonical({schema:'subscription-model-operation-v1',operation_id:operationId,operation_sha256:hash(canonical(operation)),operation})),etag:'"operation"'});
  if(resultPresent){const output={provider:spec.provider,model:spec.model,billing_route:'chatgpt_subscription',paid_fallback:false,source_sha256:chunkSha,candidates:[]},result={operation_id:operationId,spec_sha256:hash(canonical(spec)),output},body=resultPresent==='valid'?{schema:'subscription-model-result-v1',operation_id:operationId,result_sha256:hash(canonical(result)),result}:{schema:'malformed-present-result'};h.objects.set(`graph-trial/20260908/workers/cfo/${p.run.run_id}/subscription-jobs/results/${operationId}.json`,{body:Buffer.from(canonical(body)),etag:'"result"'});}
  const chunks=[{chunk_ordinal:0,operation_id:operationId,status:'unknown',receipt_sha256:hash('receipt')}],preparation={snapshot_id:snapshotId,prepared_manifest_sha256:manifest.manifest_sha256,sidecar_content_sha256:sidecarSha,chunk_count:1},outcome={status:'held',code:'dispatch_outcome_unknown',receipt_sha256:hash('held'),run_id:p.run.run_id,document_ordinal:0,recorded_at:'2026-09-09T23:30:00.000Z',chunk_receipts_sha256:hash(canonical(chunks))};
  const held={schema:'catalog-controller-version-v1',proposal:p,status:'held',outcome,chunks,preparation};h.objects.set(`${internals.BASE}/synthetic/controller/${key}.json`,{body:Buffer.from(canonical(held)),etag:'"held"'});
  const target={...held,status:'prepared',outcome:null,chunks:[]},reply=await h.request('/state/'+key,{key,revision:'"held"',value:target},'PUT');return reply.statusCode;
 }finally{await h.app.close();}}
 assert.equal(await attempt('unknown','evidence_not_in_source'),200);
 assert.equal(await attempt('unknown','evidence_not_in_source',null,'gpt-5.6-terra'),200);
 assert.equal(await attempt('unknown','evidence_not_in_source',null,'gpt-5.6-terra','e6ae7b7bd4d5518f65fc0f88c32ca2c2eee5ab40c081e4592314b457f2e8e7ff','codex-subscription-extractor-v2'),200);
 assert.equal(await attempt('unknown','evidence_not_in_source',null,'gpt-5.6-terra','e6ae7b7bd4d5518f65fc0f88c32ca2c2eee5ab40c081e4592314b457f2e8e7ff','codex-subscription-extractor-v1'),409);
 assert.equal(await attempt('unknown','evidence_not_in_source',null,'gpt-5.6-terra','a'.repeat(64)),409);
 assert.equal(await attempt('unknown','gateway_transport_unknown',null,'gpt-5.6-terra'),409);
 assert.equal(await attempt('unknown','evidence_not_in_source','valid','gpt-5.6-terra'),409);
 assert.equal(await attempt('dispatched','evidence_not_in_source'),409);
 assert.equal(await attempt('unknown','gateway_transport_unknown'),409);
 assert.equal(await attempt('unknown','evidence_not_in_source','valid'),409);
 assert.equal(await attempt('unknown','evidence_not_in_source','malformed'),409);
});



async function materializedHarness(){
 const objects=new Map<string,{body:Buffer;etag:string}>();let revision=0,sourceVersion='source-v1',sourceHeads=0,now=Date.now();
 const prefixes=['synthetic/'],sourceCatalogVersion='source-v1',catalogText=[{path:'synthetic/a.txt',sha256:hash('a'),sidecar:true,enriched:true,enriched_sha256:hash('a'),entity:'Synthetic'}].map(canonical).join('\n')+'\n';
 let catalogBody=catalogText;const logical=hash(canonical({room:'finance',source_index:'finance-cfo-source-docs',url:'https://otchealth-finance-legal-dr-55c84f6b.s3.us-east-1.amazonaws.com/otchealthcfodata/cfo-source-docs/_CATALOG/catalog.jsonl'}));
 const content=hash(catalogText),binding:any={schema:'cfo-catalog-materialization-v1',cohort_id:'materialized',policy_sha256:hash('materialized policy'),source_prefixes_sha256:hash(canonical(prefixes)),source_version_id:sourceCatalogVersion,source_etag_sha256:hash('source etag'),source_catalog_content_sha256:hash('source bytes'),source_bytes:12,catalog_content_sha256:content,catalog_source_sha256:logical,catalog_bytes:Buffer.byteLength(catalogText),counts:{source_rows:1,eligible_rows:1,duplicate_rows:0,excluded:{}},lineage:'catalog_association_only',source_current_checked:true};
 const binding_sha256=hash(canonical(binding)),catalog_key=`graph-trial/20260909/materialized-cfo/materialized/${binding_sha256}/${content}.jsonl`,receipt={...binding,status:'published',published:true,catalog_key,catalog_version_id:'catalog-v1',binding_sha256},receiptBody=Buffer.from(canonical(receipt)),receiptKey=catalog_key.replace(/\.jsonl$/,'.receipt.json');
 const cfg={cohort_id:'materialized',catalog_key,catalog_source_sha256:logical,source_prefixes:prefixes,purpose:'company_graph_backfill',run_version:'test-v1',batch_size:2,max_admissions:2,policy_sha256:binding.policy_sha256,expires_at:new Date(now+3600000).toISOString(),materialization:{catalog_content_sha256:content,source_catalog_version_id:sourceCatalogVersion,materialization_receipt_key:receiptKey,materialization_receipt_sha256:hash(receiptBody),catalog_version_id:'catalog-v1'}};
 const deps:any={configs:()=>canonical([cfg]),now:()=>now,authenticate:async()=>ctx,sourceHead:async()=>{sourceHeads++;return{status:200,headers:new Headers({'x-amz-version-id':sourceVersion}),body:Buffer.alloc(0)}},catalogS3:async(r:any)=>({status:200,headers:new Headers({etag:'"catalog-v1"','content-length':String(Buffer.byteLength(catalogBody)),'last-modified':'2026-09-08T00:00:00.000Z','x-amz-version-id':'catalog-v1'}),body:r.method==='HEAD'?null:new Response(catalogBody).body}),s3:async(r:any)=>{if(r.method==='GET'&&r.key===receiptKey)return{status:200,headers:new Headers({'x-amz-version-id':'receipt-v1'}),body:receiptBody};const prior=objects.get(r.key);if(r.method==='GET')return{status:prior?200:404,headers:new Headers(prior?{etag:prior.etag}:{}),body:prior?.body??Buffer.alloc(0)};const saved={body:Buffer.from(r.body),etag:`"${++revision}"`};objects.set(r.key,saved);return{status:200,headers:new Headers({etag:saved.etag}),body:Buffer.alloc(0)}}};
 const app=Fastify({logger:false});registerGraphCatalogControllerRoutes(app,deps);const request=(path:string,value?:unknown)=>app.inject({method:'POST',url:'/graph-catalog/v1/materialized'+path,headers:{authorization:'Bearer synthetic-cfo-token','content-type':'application/json'},payload:JSON.stringify(value)});
 return{app,request,cfg,receiptBody,receiptKey,setSourceVersion:(v:string)=>{sourceVersion=v;},setCatalogText:()=>{catalogBody=catalogBody.replace('Synthetic','SynthEtic');},get sourceHeads(){return sourceHeads;},get objectCount(){return objects.size;}};
}
test('materialized routes reject an altered catalog before planner output and preserve legacy route behavior',async()=>{const h=await materializedHarness();try{await assert.doesNotReject(verifyMaterializationReceipt({...h.cfg,materialization:h.cfg.materialization},async()=>({status:200,headers:new Headers({'x-amz-version-id':'receipt-v1'}),body:h.receiptBody}),AbortSignal.timeout(1000)));assert.ok(internals.configFor(canonical([h.cfg]),'materialized'));h.setCatalogText();const r=await h.request('/page',{cursor:null,limit:1});assert.equal(r.statusCode,503,r.body);assert.equal(h.sourceHeads,1);}finally{await h.app.close();}});
test('materialized page, publish, current retrieval, and repeat admission reject a changed upstream source version',async()=>{const h=await materializedHarness();try{const page=await h.request('/page',{cursor:null,limit:1});assert.equal(page.statusCode,200,page.body);const manifest=page.json().page.manifest,rows=page.json().page.rows;const published=await h.request('/publish',{manifest,rows});assert.equal(published.statusCode,200,published.body);const proposal=internals.proposal(h.cfg,{catalogEtag:'"catalog-v1"',catalogSourceSha256:h.cfg.catalog_source_sha256,createdAt:'2026-09-08T00:00:00.000Z'},manifest);const first=await h.request('/admit',{key:proposal.key,manifest_sha256:manifest.manifest_sha256});assert.equal(first.statusCode,200,first.body);h.setSourceVersion('source-v2');const writes=h.objectCount;const freshPage=await h.request('/page',{cursor:null,limit:1});assert.equal(freshPage.statusCode,409,freshPage.body);const stalePublish=await h.request('/publish',{manifest,rows});assert.equal(stalePublish.statusCode,409,stalePublish.body);assert.equal(h.objectCount,writes);const current=await h.request('/source-current',{item:manifest.documents[0]});assert.equal(current.statusCode,409,current.body);const currentAgain=await h.request('/source-current',{item:manifest.documents[0]});assert.equal(currentAgain.statusCode,409,currentAgain.body);const repeated=await h.request('/admit',{key:proposal.key,manifest_sha256:manifest.manifest_sha256});assert.equal(repeated.statusCode,409,repeated.body);}finally{await h.app.close();}});
