/** Default-disabled CFO cohort authority. Writable client progress never grants access. */
import { createHash } from 'node:crypto';
import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import { requireConnectorAuth, type AuthContext } from '../auth/bearer.js';
import { loadEnv } from '../config/env.js';
import { canonicalUri, resolveAwsCredentials, signRequest } from '../search/sigv4.js';
import { planGraphCatalogPage } from './graph-catalog-planner.js';
import { defaultGraphCatalogS3, readPinnedGraphCatalog, type GraphCatalogRawS3 } from './graph-catalog-reader.js';
import { CFO_SOURCE_CATALOG_KEY, MATERIALIZED_CATALOG_PREFIX, parseMaterializationPin, verifyMaterializationReceipt, type MaterializationPin } from './materialized-catalog-pin.js';
import { createCfoTextSnapshotReader, type CfoTextSource } from '../graph/cfo-text-snapshot.js';
import { resolveCompanyGraphScope, type CompanyGraphScope } from './company-graph-scope.js';
const BASE='graph-trial/20260908/catalog-cohorts', SOURCE='graph-trial/20260908/source-pilot/snapshots';
const BUCKET='otchealth-finance-legal-dr-55c84f6b',REGION='us-east-1';
const SHA=/^[a-f0-9]{64}$/, ID=/^[a-z0-9][a-z0-9_.:-]{0,95}$/, ETAG=/^"[A-Za-z0-9-]{1,128}"$/,MAX=512*1024,CFO_TEXT_CANARY_MAX_BYTES=256*1024;
type Json=Record<string,any>;
type Raw={method:'GET'|'PUT';key:string;headers?:Record<string,string>;body?:Buffer;signal:AbortSignal};
type SourceHeadRaw={method:'HEAD';key:string;signal:AbortSignal};
type Res={status:number;headers:Headers;body:Buffer};
type Run={ref_version:string;run_id:string;purpose:string;scope:string;run_version:string;manifest_sha256:string};
type Binding={authenticated_caller:'cfo'|'clo';run:Run;room:'finance'|'legal_company';source_index:'finance-cfo-source-docs'|'legal-company'};
type DeploymentProfile='finance'|'legal_company';
type Cfg={cohort_id:string;catalog_key:string;catalog_source_sha256:string;source_prefixes:string[];source_scope?:'all_cfo_source_documents';deployment_profile?:DeploymentProfile;source_catalog_version_id?:string;purpose:string;run_version:string;batch_size:number;max_admissions:number;max_active_admissions:number;policy_sha256:string;expires_at:string;recovery_policy_sha256?:string;recovery_expires_at?:string;materialization?:MaterializationPin};
type Deployment={id:DeploymentProfile;scope:CompanyGraphScope;catalogPrefix:string;snapshotPrefix:string;sourceCatalogKey:string;publicationPrefix:string;producerId:string};
export interface GraphCatalogDeps{authenticate:(r:FastifyRequest,p:FastifyReply)=>Promise<AuthContext|undefined>;configs:()=>string;s3:(r:Raw)=>Promise<Res>;sourceHead?:(r:SourceHeadRaw)=>Promise<Res>;readCfoText?:(source:CfoTextSource,signal:AbortSignal)=>Promise<any>;now:()=>number;catalogS3?:GraphCatalogRawS3;}
const hash=(v:string|Buffer)=>createHash('sha256').update(v).digest('hex');
const canonical=(v:any):string=>v===null||typeof v!=='object'?JSON.stringify(v):Array.isArray(v)?'['+v.map(canonical).join(',')+']':'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}';
const equal=(a:any,b:any)=>canonical(a)===canonical(b);
const exact=(v:any,k:string[])=>!!v&&Object.getPrototypeOf(v)===Object.prototype&&Object.keys(v).sort().join('\0')===k.slice().sort().join('\0');
const path=(c:Cfg,s:string)=>`${BASE}/${c.cohort_id}/${s}`;
const validPath=(s:unknown):s is string=>typeof s==='string'&&s.length>0&&s.length<=1024&&s===s.normalize('NFC')&&!s.startsWith('/')&&!/[\\%?#:\u0000-\u001f\u007f]/.test(s)&&s.split('/').every(p=>p!==''&&p!=='.'&&p!=='..');
const DEPLOYMENTS:Readonly<Record<DeploymentProfile,Omit<Deployment,'scope'>>>=Object.freeze({
 finance:Object.freeze({id:'finance',catalogPrefix:'graph-trial/',snapshotPrefix:SOURCE,sourceCatalogKey:CFO_SOURCE_CATALOG_KEY,publicationPrefix:'graph-trial/20260908/relationship-publications/cfo',producerId:'cfo-relationship-worker'}),
 legal_company:Object.freeze({id:'legal_company',catalogPrefix:'graph-trial/20260912/legal-company/catalogs/',snapshotPrefix:'graph-trial/20260912/legal-company/catalog-snapshots',sourceCatalogKey:'otchealthlegalstore/company/_CATALOG/catalog.jsonl',publicationPrefix:'graph-trial/20260912/relationship-publications/clo',producerId:'clo-relationship-worker'}),
});
function deployment(c:Cfg):Deployment{const id=c.deployment_profile??'finance',raw=DEPLOYMENTS[id],resolved=resolveCompanyGraphScope(id==='finance'?'cfo':'clo',id);if(!raw||!resolved.ok)fail(503,'graph_catalog_configuration_invalid');return{...raw,scope:resolved.scope};}
function workerPrefix(c:Cfg){return deployment(c).scope.workerStore.prefix.replace(/\/$/,'');}
function sourceSnapshotKey(c:Cfg,suffix:string){return `${deployment(c).snapshotPrefix}/${suffix}`;}
function sourceSnapshotRowKey(c:Cfg,item:Json){return sourceSnapshotKey(c,`rows/${deployment(c).scope.room}/${item.enrichment_row_sha256}.json`);}
function sourceSnapshotManifestKey(c:Cfg,manifest:Json){return sourceSnapshotKey(c,`manifests/${manifest.manifest_sha256}.json`);}
function fail(status=503,code='graph_catalog_unavailable'):never{throw Object.assign(new Error(code),{status,code});}
function active(signal:AbortSignal){if(signal.aborted)fail(503,'graph_catalog_cancelled');}
async function bounded<T>(fn:()=>Promise<T>,signal:AbortSignal):Promise<T>{
 active(signal);return new Promise((resolve,reject)=>{const cleanup=()=>signal.removeEventListener('abort',abort);const abort=()=>{cleanup();reject(Object.assign(new Error('graph_catalog_cancelled'),{status:503,code:'graph_catalog_cancelled'}));};signal.addEventListener('abort',abort,{once:true});Promise.resolve().then(()=>{active(signal);return fn();}).then(v=>{cleanup();resolve(v);},e=>{cleanup();reject(e);});if(signal.aborted)abort();});
}
function configFor(text:string,id:string):Cfg|null{
 try{if(text.length>65536)return null;const all=JSON.parse(text);if(!Array.isArray(all)||all.length>32)return null;const found=all.filter(x=>x?.cohort_id===id);if(found.length!==1)return null;const c=found[0],keys=['cohort_id','catalog_key','catalog_source_sha256','source_prefixes','purpose','run_version','batch_size','max_admissions','policy_sha256','expires_at'];
 const recovery=['recovery_policy_sha256','recovery_expires_at'],materialization=['materialization'],scope=['source_scope'],profileField=['deployment_profile'],sourcePin=['source_catalog_version_id'];
 const shapes=[keys,[...keys,...recovery],[...keys,...materialization],[...keys,...recovery,...materialization],[...keys,...scope],[...keys,...scope,...materialization],[...keys,...scope,...recovery],[...keys,...scope,...recovery,...materialization]];
 const expanded=shapes.flatMap(shape=>[shape,[...shape,...profileField],[...shape,...profileField,...sourcePin],[...shape,'max_active_admissions'],[...shape,...profileField,'max_active_admissions'],[...shape,...profileField,...sourcePin,'max_active_admissions']]);
 if(!expanded.some(shape=>exact(c,shape)))return null;
 const date=(v:unknown)=>typeof v==='string'&&Number.isFinite(Date.parse(v))&&new Date(v).toISOString()===v;
 if(!ID.test(c.cohort_id)||!validPath(c.catalog_key)||!c.catalog_key.startsWith('graph-trial/')||!c.catalog_key.endsWith('.jsonl')||!SHA.test(c.catalog_source_sha256)||!ID.test(c.purpose)||!ID.test(c.run_version)||!SHA.test(c.policy_sha256)||!date(c.expires_at)||!Number.isInteger(c.batch_size)||c.batch_size<1||c.batch_size>10||!Number.isInteger(c.max_admissions)||c.max_admissions<0||c.max_admissions>1000||!Array.isArray(c.source_prefixes))return null;
 c.max_active_admissions??=1;if(!Number.isInteger(c.max_active_admissions)||c.max_active_admissions<1||c.max_active_admissions>2||(c.max_admissions>0&&c.max_active_admissions>c.max_admissions))return null;
 if(c.deployment_profile!==undefined&&!['finance','legal_company'].includes(c.deployment_profile))return null;
 const profile=deployment(c),allScope=c.source_scope==='all_cfo_source_documents';
 if(c.source_scope!==undefined&&!allScope)return null;
 if(profile.id==='legal_company'&&(allScope||typeof c.source_catalog_version_id!=='string'||!validPath(c.source_catalog_version_id)))return null;
 if(profile.id==='finance'&&c.source_catalog_version_id!==undefined)return null;
  const invalidPrefixes = c.source_prefixes.length<1 || c.source_prefixes.length>16 ||
    !c.source_prefixes.every((p:any)=>typeof p==='string'&&p.endsWith('/')&&validPath(p.slice(0,-1))) ||
    new Set(c.source_prefixes).size!==c.source_prefixes.length;
  if(allScope ? c.source_prefixes.length!==0 : invalidPrefixes)return null;
 if(c.recovery_policy_sha256!==undefined&&(!SHA.test(c.recovery_policy_sha256)||!date(c.recovery_expires_at)))return null;
 const pin=c.materialization===undefined?undefined:parseMaterializationPin(c.materialization);
 if(c.materialization!==undefined&&!pin)return null;
 if(!c.catalog_key.startsWith(profile.catalogPrefix)||c.catalog_key.startsWith(MATERIALIZED_CATALOG_PREFIX)!==!!pin||allScope&&!pin)return null;
 if(profile.id==='legal_company'&&pin)return null;
 if(pin)c.materialization=pin;
 return c;}catch{return null;}
}
async function defaultS3(r:Raw):Promise<Res>{
 if(!r.key.startsWith('graph-trial/'))fail(403,'graph_catalog_forbidden');
 active(r.signal);const credentials=await bounded(()=>resolveAwsCredentials(),r.signal);if(!credentials)fail();active(r.signal);
 const host=`${BUCKET}.s3.${REGION}.amazonaws.com`,signed=signRequest({method:r.method,host,path:'/'+r.key,region:REGION,service:'s3',credentials,...(r.body?{body:r.body}:{}),extraHeaders:{'x-amz-content-sha256':hash(r.body??Buffer.alloc(0)),...(r.headers??{})}});
 const response=await bounded(()=>fetch('https://'+host+canonicalUri('/'+r.key),{method:r.method,headers:signed.headers,body:r.body,signal:r.signal,redirect:'error'}),r.signal);
 if(Number(response.headers.get('content-length'))>MAX)fail();const reader=response.body?.getReader(),parts:Buffer[]=[];let size=0;
 try{if(reader)for(;;){const x=await bounded(()=>reader.read(),r.signal);active(r.signal);if(x.done)break;size+=x.value.byteLength;if(size>MAX)fail();parts.push(Buffer.from(x.value));}return{status:response.status,headers:response.headers,body:Buffer.concat(parts,size)};}
 finally{if(reader){let timer:ReturnType<typeof setTimeout>|undefined;await Promise.race([reader.cancel().catch(()=>undefined),new Promise(resolve=>{timer=setTimeout(resolve,100);})]);clearTimeout(timer);}}
}
async function defaultSourceHead(r:SourceHeadRaw):Promise<Res>{
 if(!Object.values(DEPLOYMENTS).some(profile=>profile.sourceCatalogKey===r.key))fail(403,'graph_catalog_forbidden');active(r.signal);const credentials=await bounded(()=>resolveAwsCredentials(),r.signal);if(!credentials)fail();
 const host=`${BUCKET}.s3.${REGION}.amazonaws.com`,signed=signRequest({method:'HEAD',host,path:'/'+r.key,region:REGION,service:'s3',credentials,extraHeaders:{'x-amz-content-sha256':hash(Buffer.alloc(0))}});
 const response=await bounded(()=>fetch('https://'+host+canonicalUri('/'+r.key),{method:'HEAD',headers:signed.headers,signal:r.signal,redirect:'error'}),r.signal);
 return {status:response.status,headers:response.headers,body:Buffer.alloc(0)};
}
function depsOf(i?:Partial<GraphCatalogDeps>):GraphCatalogDeps{return{authenticate:i?.authenticate??requireConnectorAuth,configs:i?.configs??(()=>loadEnv().GRAPH_CATALOG_COHORTS_JSON),s3:i?.s3??defaultS3,sourceHead:i?.sourceHead??defaultSourceHead,readCfoText:i?.readCfoText??((source,signal)=>createCfoTextSnapshotReader({callerContext:{caller_agent:'cfo',connector_surface:true},maxSourceBytes:CFO_TEXT_CANARY_MAX_BYTES}).readVersionPinnedPage(source,{signal})),now:i?.now??Date.now,catalogS3:i?.catalogS3};}
async function get(d:GraphCatalogDeps,k:string,s:AbortSignal):Promise<{value:Json;etag:string;raw:Res}|null>{
 const r=await bounded(()=>d.s3({method:'GET',key:k,signal:s}),s);active(s);if(r.status===404)return null;if(r.status!==200||r.body.length>MAX||!ETAG.test(r.headers.get('etag')??''))fail();let v;try{v=JSON.parse(r.body.toString('utf8'));}catch{fail();}if(!v||typeof v!=='object'||Array.isArray(v))fail();return{value:v,etag:r.headers.get('etag')!,raw:r};
}
async function cas(d:GraphCatalogDeps,k:string,prior:{etag:string}|null,v:any,s:AbortSignal):Promise<boolean>{
 active(s);const body=Buffer.from(canonical(v));if(body.length>MAX)fail(400,'graph_catalog_request_invalid');const r=await bounded(()=>d.s3({method:'PUT',key:k,headers:{'content-type':'application/json',...(prior?{'if-match':prior.etag}:{'if-none-match':'*'})},body,signal:s}),s);active(s);if([409,412].includes(r.status))return false;if(![200,201].includes(r.status))fail();const saved=await get(d,k,s);if(!saved||!equal(saved.value,v))fail();return true;
}
async function immutable(d:GraphCatalogDeps,k:string,v:any,s:AbortSignal){const old=await get(d,k,s);if(old){if(!equal(old.value,v))fail(409,'graph_catalog_immutable_conflict');return;}await cas(d,k,null,v,s);const saved=await get(d,k,s);if(!saved||!equal(saved.value,v))fail();}
function controllerId(c:Cfg){const profile=deployment(c);if(profile.id==='finance')return hash(canonical({schema:'catalog-controller-v1',room:'finance',catalogSourceSha256:c.catalog_source_sha256,purpose:c.purpose,runVersion:c.run_version}));return hash(canonical({schema:'catalog-controller-v2',deploymentProfile:profile.id,room:profile.scope.room,catalogSourceSha256:c.catalog_source_sha256,purpose:c.purpose,runVersion:c.run_version,sourceCatalogVersionId:c.source_catalog_version_id}));}
function targetRunVersion(c:Cfg){return 'promotion-'+hash(canonical({controller_id:controllerId(c),kind:'targeted-promotion'})).slice(0,32);}
function run(c:Cfg,m:string,kind:'ordinary'|'targeted-promotion'='ordinary'):Run{const x={ref_version:'neptune-trial-active-run-ref-v1',purpose:c.purpose,scope:deployment(c).scope.scope,run_version:kind==='ordinary'?c.run_version:targetRunVersion(c),manifest_sha256:m};return{...x,run_id:'run_'+hash(canonical(x))};}
function validItem(x:any,c?:Cfg){const profile=c?deployment(c):deployment({deployment_profile:'finance'} as Cfg);return exact(x,['ordinal','room','document_version_id','source_version','source_path_hash','enrichment_row_sha256','extractor_version','retract_event_ids'])&&x.ordinal===0&&x.room===profile.scope.room&&/^docv_[a-f0-9]{64}$/.test(x.document_version_id)&&['source_version','source_path_hash','enrichment_row_sha256'].every(k=>SHA.test(x[k]))&&x.extractor_version==='catalog-mention-snapshot-v1'&&Array.isArray(x.retract_event_ids)&&x.retract_event_ids.length===0;}
function validManifest(m:any,c?:Cfg){if(!exact(m,['version','created_at','documents','manifest_sha256'])||m.version!=='graph-backfill-runner-v1'||!Array.isArray(m.documents)||m.documents.length!==1||!validItem(m.documents[0],c)||!SHA.test(m.manifest_sha256))return false;const{manifest_sha256,...body}=m;return manifest_sha256===hash(canonical(body));}
async function sourceHead(d:GraphCatalogDeps,c:Cfg,expectedVersion:string,s:AbortSignal){
 const raw=await bounded(()=>(d.sourceHead??defaultSourceHead)({method:'HEAD',key:deployment(c).sourceCatalogKey,signal:s}),s),version=raw.headers.get('x-amz-version-id');
 if(raw.status!==200||version!==expectedVersion)fail(409,'graph_catalog_source_changed');
 return version;
}
function sourceRowAllowed(c:Cfg,row:Record<string,unknown>):boolean{
 const pathValue=row.path;if(typeof pathValue!=='string')return false;
 const profile=deployment(c);
 if(profile.id==='legal_company')return c.source_prefixes.some(prefix=>pathValue.startsWith(prefix));
 if(c.source_scope!=='all_cfo_source_documents')return c.source_prefixes.some(prefix=>pathValue.startsWith(prefix));
 if(!validPath(pathValue))return false;
 return !['_text','_catalog','_review','_memory','_state','_archive'].includes(pathValue.split('/')[0].toLowerCase());
}
async function catalog(d:GraphCatalogDeps,c:Cfg,s:AbortSignal){
 const pin=c.materialization;
 if(!pin){
  const deploymentProfile=deployment(c);
  if(deploymentProfile.id==='legal_company')await sourceHead(d,c,c.source_catalog_version_id!,s);
  const read=await readPinnedGraphCatalog({key:c.catalog_key,sourceSha256:c.catalog_source_sha256,s3:d.catalogS3,signal:s});
  if(deploymentProfile.id==='legal_company')await sourceHead(d,c,c.source_catalog_version_id!,s);
  return{...read,rows:read.rows.filter(row=>sourceRowAllowed(c,row))};
 }
 await verifyMaterializationReceipt({cohort_id:c.cohort_id,policy_sha256:c.policy_sha256,source_prefixes:c.source_prefixes,source_scope:c.source_scope,catalog_key:c.catalog_key,catalog_source_sha256:c.catalog_source_sha256,materialization:pin},async request=>{
  return await bounded(()=>d.s3({method:'GET',key:request.key,signal:request.signal}),request.signal);
 },s);
 await sourceHead(d,c,pin.source_catalog_version_id,s);
 const read=await readPinnedGraphCatalog({key:c.catalog_key,sourceSha256:c.catalog_source_sha256,expectedContentSha256:pin.catalog_content_sha256,expectedVersionId:pin.catalog_version_id,s3:d.catalogS3??defaultGraphCatalogS3,signal:s});
 await sourceHead(d,c,pin.source_catalog_version_id,s);
 return {...read,rows:read.rows.filter(row=>sourceRowAllowed(c,row))};
}
function proposal(c:Cfg,cat:any,m:any,kind:'ordinary'|'targeted-promotion'='ordinary'){const item=m.documents[0],id=controllerId(c),key=hash(canonical({controller_id:id,document_version_id:item.document_version_id,source_version:item.source_version,enrichment_row_sha256:item.enrichment_row_sha256,extractor_version:item.extractor_version,...(kind==='ordinary'?{}:{selection:kind})}));return{controller_id:id,key,catalog_snapshot_sha256:hash(canonical({source:c.catalog_source_sha256,etag:cat.catalogEtag,createdAt:cat.createdAt})),catalog_source_sha256:c.catalog_source_sha256,catalog_etag_sha256:hash(cat.catalogEtag),manifest:m,run:run(c,m.manifest_sha256,kind),max_documents:1,document_ordinal:0,paid_fallback:false,requires_review:true};}
function proposalKind(c:Cfg,p:any):'ordinary'|'targeted-promotion'|null{const item=p?.manifest?.documents?.[0];if(!item)return null;for(const kind of ['ordinary','targeted-promotion'] as const){const expected=proposal(c,{catalogEtag:'placeholder',catalog_source_sha256:c.catalog_source_sha256,createdAt:'2000-01-01T00:00:00.000Z'},p.manifest,kind);if(p.key===expected.key&&equal(p.run,expected.run))return kind;}return null;}
async function current(d:GraphCatalogDeps,c:Cfg,item:any,s:AbortSignal){const cat=await catalog(d,c,s);for(const row of cat.rows){if(hash(String(row.path))!==item.source_path_hash)continue;const p=planGraphCatalogPage({...cat,scope:deployment(c).scope,rows:[row],limit:1});if(p.page.manifest&&equal(p.page.manifest.documents[0],item))return true;}return false;}
async function serverProposal(d:GraphCatalogDeps,c:Cfg,key:string,s:AbortSignal){if(!SHA.test(key))fail(400,'graph_catalog_request_invalid');const p=await get(d,path(c,`server/proposals/${key}.json`),s);if(!p||p.value.key!==key||p.value.controller_id!==controllerId(c)||!validManifest(p.value.manifest,c)||!proposalKind(c,p.value))fail(409,'graph_catalog_proposal_missing');return p.value;}
function live(c:Cfg,d:GraphCatalogDeps){return c.max_admissions>0&&Date.parse(c.expires_at)>d.now();}
function recoveryLive(c:Cfg,d:GraphCatalogDeps){return !!c.recovery_policy_sha256&&!!c.recovery_expires_at&&Date.parse(c.recovery_expires_at)>d.now();}
async function receipt(d:GraphCatalogDeps,c:Cfg,runId:string,s:AbortSignal){if(!/^run_[a-f0-9]{64}$/.test(runId))fail(400,'graph_catalog_request_invalid');const saved=await get(d,path(c,`server/admissions/${runId}.json`),s);if(!saved)fail(403,'graph_catalog_admission_missing');const v=saved.value,{decision_sha256,...unsigned}=v;if(!exact(v,['allowed','key','run_id','manifest_sha256','max_documents','policy_sha256','decision_sha256'])||v.allowed!==true||v.max_documents!==1||v.policy_sha256!==c.policy_sha256||v.run_id!==runId||hash(canonical(unsigned))!==decision_sha256)fail();const p=await serverProposal(d,c,v.key,s);if(p.run.run_id!==runId||p.manifest.manifest_sha256!==v.manifest_sha256)fail();return{receipt:v,proposal:p};}
type ControlEntry={status:'reserved'|'active';key:string;run_id:string;manifest_sha256:string};
function validControlEntry(v:any):v is ControlEntry{return exact(v,['status','key','run_id','manifest_sha256'])&&['reserved','active'].includes(v.status)&&SHA.test(v.key)&&/^run_[a-f0-9]{64}$/.test(v.run_id)&&SHA.test(v.manifest_sha256);}
async function control(d:GraphCatalogDeps,c:Cfg,s:AbortSignal){const saved=await get(d,path(c,'server/control.json'),s);if(!saved)return null;const v=saved.value;let entries:ControlEntry[];
 if(exact(v,['schema','policy_sha256','used','current'])&&v.schema==='graph-catalog-control-v1'&&v.policy_sha256===c.policy_sha256&&Number.isInteger(v.used)&&v.used>=1&&v.used<=1000&&validControlEntry(v.current))entries=[v.current];
 else if(exact(v,['schema','policy_sha256','used','active'])&&v.schema==='graph-catalog-control-v2'&&v.policy_sha256===c.policy_sha256&&Number.isInteger(v.used)&&v.used>=1&&v.used<=1000&&Array.isArray(v.active)&&v.active.length>=1&&v.active.length<=c.max_active_admissions&&v.active.every(validControlEntry)&&new Set(v.active.map((x:any)=>x.key)).size===v.active.length&&new Set(v.active.map((x:any)=>x.run_id)).size===v.active.length)entries=v.active;
 else fail();for(const entry of entries){const p=await serverProposal(d,c,entry.key,s);if(p.run.run_id!==entry.run_id||p.manifest.manifest_sha256!==entry.manifest_sha256)fail();}return{...saved,entries};}
function activeFor(ctl:Awaited<ReturnType<typeof control>>,runId:string){return ctl?.entries.find(entry=>entry.status==='active'&&entry.run_id===runId)??null;}
function controlV2(c:Cfg,used:number,entries:ControlEntry[]){if(!Number.isInteger(used)||used<1||entries.length<1||entries.length>c.max_active_admissions||entries.some(entry=>!validControlEntry(entry)))fail();return{schema:'graph-catalog-control-v2',policy_sha256:c.policy_sha256,used,active:entries};}
async function preparation(d:GraphCatalogDeps,c:Cfg,p:Json,value:Json,s:AbortSignal){
 const prep=value.preparation;if(!exact(prep,['snapshot_id','prepared_manifest_sha256','sidecar_content_sha256','chunk_count'])||!/^txtsnap_[a-f0-9]{64}$/.test(prep.snapshot_id)||!SHA.test(prep.prepared_manifest_sha256)||!SHA.test(prep.sidecar_content_sha256)||!Number.isInteger(prep.chunk_count)||prep.chunk_count<1||prep.chunk_count>100)return null;
 const saved=await get(d,`${workerPrefix(c)}/${p.run.run_id}/text-snapshots/${prep.snapshot_id}/manifest.json`,s);if(!saved)return null;const m=saved.value,{manifest_sha256,...content}=m;
 const profile=deployment(c),manifestSchema=profile.id==='finance'?'cfo-text-prepared-manifest-v1':'company-text-prepared-manifest-v1';
 if(m.schema!==manifestSchema||manifest_sha256!==prep.prepared_manifest_sha256||manifest_sha256!==hash(canonical(content))||m.snapshot_id!==prep.snapshot_id||!m.identity||m.identity.run_id!==p.run.run_id||m.identity.document_ordinal!==0||`txtsnap_${hash(canonical(m.identity))}`!==m.snapshot_id||m.identity.descriptor?.source_document_version!==p.manifest.documents[0].document_version_id||m.identity.descriptor?.sidecar_content_sha256!==prep.sidecar_content_sha256||!Array.isArray(m.chunks)||m.chunks.length!==prep.chunk_count)return null;
 return m;
}
async function boundOperation(d:GraphCatalogDeps,c:Cfg,p:Json,value:Json,ordinal:number,s:AbortSignal){
 const m=await preparation(d,c,p,value,s),chunk=value.chunks?.[ordinal];if(!m||!chunk||chunk.chunk_ordinal!==ordinal||!/^subop_[a-f0-9]{64}$/.test(chunk.operation_id))return null;
 const raw=await get(d,`${workerPrefix(c)}/${p.run.run_id}/subscription-jobs/operations/${chunk.operation_id}.json`,s);if(!raw)return null;const env=raw.value,o=env.operation,spec=o?.spec,b=spec?.source_binding,ref=m.chunks[ordinal],profile=deployment(c);
 if(env.schema!=='subscription-model-operation-v1'||env.operation_id!==chunk.operation_id||env.operation_sha256!==hash(canonical(o))||o.operation_id!==chunk.operation_id||chunk.operation_id!==`subop_${hash(canonical(spec))}`||spec.purpose!==p.run.purpose||!b||b.schema!==(profile.id==='finance'?'cfo-prepared-chunk-binding-v1':'company-prepared-chunk-binding-v1')||b.run_id!==p.run.run_id||b.room!==profile.scope.room||b.source_index!==profile.scope.sourceIndex||b.catalog_manifest_sha256!==p.manifest.manifest_sha256||b.document_ordinal!==0||b.source_document_version!==p.manifest.documents[0].document_version_id||b.catalog_source_sha256!==p.manifest.documents[0].source_version||b.snapshot_id!==m.snapshot_id||b.prepared_manifest_sha256!==m.manifest_sha256||b.sidecar_content_sha256!==value.preparation.sidecar_content_sha256||b.chunk_ordinal!==ordinal||ref.ordinal!==ordinal||b.chunk_sha256!==ref.text_sha256)return null;
 return{raw,spec,chunk,binding:b};
}
async function resultFor(d:GraphCatalogDeps,c:Cfg,p:Json,op:NonNullable<Awaited<ReturnType<typeof boundOperation>>>,s:AbortSignal){const saved=await get(d,`${workerPrefix(c)}/${p.run.run_id}/subscription-jobs/results/${op.chunk.operation_id}.json`,s);if(!saved)return null;const env=saved.value,r=env.result,out=r?.output;
 if(env.schema!=='subscription-model-result-v1'||env.operation_id!==op.chunk.operation_id||env.result_sha256!==hash(canonical(r))||r.operation_id!==op.chunk.operation_id||r.spec_sha256!==hash(canonical(op.spec))||out?.provider!==op.spec.provider||out?.model!==op.spec.model||out.billing_route!=='chatgpt_subscription'||out.paid_fallback!==false||out.source_sha256!==op.binding.chunk_sha256||!Array.isArray(out.candidates))return null;return saved;
}
function validRun(v:any,c?:Cfg){const scope=c?deployment(c).scope.scope:'finance';if(!exact(v,['ref_version','run_id','purpose','scope','run_version','manifest_sha256'])||v.ref_version!=='neptune-trial-active-run-ref-v1'||v.scope!==scope||!ID.test(v.purpose)||!ID.test(v.run_version)||!SHA.test(v.manifest_sha256)||!/^run_[a-f0-9]{64}$/.test(v.run_id))return false;const{run_id,...core}=v;return run_id==='run_'+hash(canonical(core));}
function validArtifact(v:any){return exact(v,['schema','artifact_id','bucket','key','payload_sha256','version_id','size_bytes'])&&v.schema==='relationship-resolution-artifact-ref-v1'&&v.bucket===BUCKET&&v.artifact_id===`resart_${v.payload_sha256}`&&SHA.test(v.payload_sha256)&&validPath(v.key)&&v.key===`resolution-artifacts/sha256/${v.payload_sha256.slice(0,2)}/${v.payload_sha256}.json`&&typeof v.version_id==='string'&&v.version_id!=='null'&&v.version_id.length>0&&v.version_id.length<=1024&&!/[\s\p{C}]/u.test(v.version_id)&&Number.isSafeInteger(v.size_bytes)&&v.size_bytes>=0&&v.size_bytes<=16777216;}
function validPromotionSource(v:any,p:Json){return exact(v,['source_document_version','catalog_source_sha256','chunk_sha256'])&&v.source_document_version===p.manifest.documents[0].document_version_id&&v.catalog_source_sha256===p.manifest.documents[0].source_version&&SHA.test(v.chunk_sha256);}
function promotionInput(c:Cfg,p:Json,b:any){const profile=deployment(c);if(proposalKind(c,p)!=='targeted-promotion'||!exact(b,['key','run_id','artifact_ref','producer_id','parent_run','parent_artifact_ref','source_refs','source_refs_sha256'])||b.key!==p.key||b.run_id!==p.run.run_id||b.producer_id!==profile.producerId||!validArtifact(b.artifact_ref)||!validRun(b.parent_run,c)||b.parent_run.run_id===p.run.run_id||!validArtifact(b.parent_artifact_ref)||!Array.isArray(b.source_refs)||b.source_refs.length<1||b.source_refs.length>1000||b.source_refs.some((x:any)=>!validPromotionSource(x,p)))return null;const refs=b.source_refs.map((x:any)=>structuredClone(x));if(new Set(refs.map(canonical)).size!==refs.length||canonical(refs)!==canonical([...refs].sort((a,b)=>canonical(a).localeCompare(canonical(b))))||b.source_refs_sha256!==hash(canonical(refs)))return null;return{key:p.key,run_id:p.run.run_id,artifact_ref:structuredClone(b.artifact_ref),producer_id:b.producer_id,parent_run:structuredClone(b.parent_run),parent_artifact_ref:structuredClone(b.parent_artifact_ref),source_refs:refs,source_refs_sha256:b.source_refs_sha256};}
type PublicationGrantInput={producer_id:string;artifact_ref:any};
function publicationGrant(v:any,c:Cfg,p:Json,input:PublicationGrantInput){return exact(v,['schema','cohort_id','producer_id','caller_hash','run','admission','proposal','artifact_ref','approved_artifacts','issued_under_policy_version'])&&v.schema==='relationship-publication-grant-v1'&&v.cohort_id===c.cohort_id&&v.producer_id===input.producer_id&&SHA.test(v.caller_hash)&&equal(v.run,p.run)&&equal(v.artifact_ref,input.artifact_ref)&&Array.isArray(v.approved_artifacts)&&v.approved_artifacts.some((x:any)=>exact(x,['digest','version_id'])&&x.digest===input.artifact_ref.payload_sha256&&x.version_id===input.artifact_ref.version_id)&&ID.test(v.issued_under_policy_version);}
async function promotionCompleted(d:GraphCatalogDeps,c:Cfg,p:Json,s:AbortSignal){if(proposalKind(c,p)!=='targeted-promotion')return false;const completed=await get(d,path(c,`server/promotion-completions/${p.key}.json`),s);if(!completed)return false;const v=completed.value;if(!exact(v,['schema','key','run_id','artifact_ref','parent_run','parent_artifact_ref','source_refs','source_refs_sha256','lineage_sha256','publication_grant_sha256'])||v.schema!=='graph-catalog-promotion-completion-v1'||v.key!==p.key||v.run_id!==p.run.run_id||!SHA.test(v.lineage_sha256)||!SHA.test(v.publication_grant_sha256))return false;const profile=deployment(c),input=promotionInput(c,p,{key:v.key,run_id:v.run_id,artifact_ref:v.artifact_ref,producer_id:profile.producerId,parent_run:v.parent_run,parent_artifact_ref:v.parent_artifact_ref,source_refs:v.source_refs,source_refs_sha256:v.source_refs_sha256});if(!input)return false;const lineage=await get(d,path(c,`server/promotion-lineages/${p.key}.json`),s);if(!lineage||hash(lineage.raw.body)!==v.lineage_sha256||!equal(lineage.value,{schema:'graph-catalog-promotion-lineage-v1',...input}))return false;const grant=await get(d,`${profile.publicationPrefix}/${c.cohort_id}/${profile.producerId}/runs/${p.run.run_id}.json`,s);return !!grant&&hash(grant.raw.body)===v.publication_grant_sha256&&publicationGrant(grant.value,c,p,input);}
async function ordinaryPublicationCompleted(d:GraphCatalogDeps,c:Cfg,p:Json,s:AbortSignal){const profile=deployment(c),grant=await get(d,`${profile.publicationPrefix}/${c.cohort_id}/${profile.producerId}/runs/${p.run.run_id}.json`,s),artifact_ref=grant?.value?.artifact_ref;return !!grant&&publicationGrant(grant.value,c,p,{producer_id:profile.producerId,artifact_ref});}
async function extractionCompleted(d:GraphCatalogDeps,c:Cfg,p:Json,value:Json,s:AbortSignal){if(!value.preparation||!Array.isArray(value.chunks)||value.chunks.length!==value.preparation.chunk_count||!value.chunks.length)return false;for(let n=0;n<value.chunks.length;n++){const op=await boundOperation(d,c,p,value,n,s);if(!op||!await resultFor(d,c,p,op,s))return false;}return true;}
async function completed(d:GraphCatalogDeps,c:Cfg,p:Json,value:Json,s:AbortSignal){return proposalKind(c,p)==='targeted-promotion'?promotionCompleted(d,c,p,s):extractionCompleted(d,c,p,value,s);}
function validOversizeReceipt(p:Json,value:Json){const o=value?.outcome;if(value?.status!=='deferred'||value.preparation!==null||!Array.isArray(value.chunks)||value.chunks.length!==0||o?.code!=='oversize'||o.chunk_receipts_sha256!==hash(canonical([])))return false;const receipt={schema:'company-prepared-text-worker-receipt-v1',run_id:p.run.run_id,document_ordinal:0,status:'deferred',code:'oversize',completed_chunks:0,paid_fallback:false};return o.receipt_sha256===hash(canonical(receipt));}
async function verifiedOversizeDeferral(d:GraphCatalogDeps,c:Cfg,p:Json,value:Json,s:AbortSignal){if(deployment(c).id!=='finance'||!validOversizeReceipt(p,value))return false;const item=p.manifest?.documents?.[0],saved=await get(d,sourceSnapshotRowKey(c,item??{}),s),row=saved?.value?.row;if(!item||!saved||!exact(saved.value,['schema','room','document_version_id','row'])||saved.value.schema!=='catalog-mention-snapshot-v1'||saved.value.room!=='finance'||saved.value.document_version_id!==item.document_version_id||!row||Object.getPrototypeOf(row)!==Object.prototype||!validPath(row.path)||hash(row.path)!==item.source_path_hash)return false;try{const observed=await d.readCfoText!(Object.freeze({room:'finance',source_index:'finance-cfo-source-docs',path:row.path,source_path_hash:item.source_path_hash,document_version_id:item.document_version_id,source_version:item.source_version}),s);return observed?.outcome==='oversize'&&observed.source_document_version===item.document_version_id&&observed.catalog_source_sha256===item.source_version&&Number.isSafeInteger(observed.observed_bytes)&&observed.observed_bytes>CFO_TEXT_CANARY_MAX_BYTES;}catch{return false;}}
async function settled(d:GraphCatalogDeps,c:Cfg,p:Json,value:Json,s:AbortSignal){if(value?.status==='deferred')return verifiedOversizeDeferral(d,c,p,value,s);if(proposalKind(c,p)==='targeted-promotion')return promotionCompleted(d,c,p,s);return await extractionCompleted(d,c,p,value,s)&&await ordinaryPublicationCompleted(d,c,p,s);}async function validateState(d:GraphCatalogDeps,c:Cfg,key:string,value:Json,prior:Json|null,s:AbortSignal){
 if(key==='cursor'){
  if(!exact(value,['schema','controller_id','snapshot','cursor','done','pending'])||value.schema!=='catalog-controller-cursor-v1'||value.controller_id!==controllerId(c)||typeof value.done!=='boolean'||!(value.snapshot===null||SHA.test(value.snapshot))||!Array.isArray(value.pending)||value.pending.length>10||new Set(value.pending).size!==value.pending.length||value.pending.some((v:any)=>!SHA.test(v)))fail(400,'graph_catalog_state_invalid');
  if(value.cursor!==null&&(!exact(value.cursor,['room','catalog_source_sha256','catalog_etag_sha256','after_document_id'])||value.cursor.room!==deployment(c).scope.room||value.cursor.catalog_source_sha256!==c.catalog_source_sha256||!SHA.test(value.cursor.catalog_etag_sha256)||!/^docv_[a-f0-9]{64}$/.test(value.cursor.after_document_id)))fail(400,'graph_catalog_state_invalid');
  for(const pending of value.pending)await serverProposal(d,c,pending,s);return;
 }
 const p=await serverProposal(d,c,key.slice(9),s);
 if(!exact(value,['schema','proposal','status','outcome','chunks','preparation'])||value.schema!=='catalog-controller-version-v1'||!equal(value.proposal,p)||!['prepared','dispatching','held','complete','deferred'].includes(value.status)||!Array.isArray(value.chunks)||value.chunks.length>100)fail(400,'graph_catalog_state_invalid');
 if(!prior&&(value.status!=='prepared'||value.outcome!==null||value.preparation!==null||value.chunks.length))fail(409,'graph_catalog_state_transition');
 if(prior){if(!equal(prior.proposal,value.proposal))fail(409,'graph_catalog_state_transition');if(value.status==='deferred'&&value.outcome.code==='oversize'&&!await verifiedOversizeDeferral(d,c,p,value,s))fail(409,'graph_catalog_deferral_unconfirmed');let resume=false,retry=false;
  if(recoveryLive(c,d)&&['dispatching','held'].includes(prior.status)&&value.status==='prepared'&&value.outcome===null&&prior.preparation===null&&value.preparation===null&&prior.chunks.length===0&&value.chunks.length===0){
   try{const a=await receipt(d,c,p.run.run_id,s),active=activeFor(await control(d,c,s),p.run.run_id);resume=a.receipt.key===p.key&&active?.key===p.key;}catch{resume=false;}
  }
  if(recoveryLive(c,d)&&prior.status==='held'&&prior.outcome?.code==='dispatch_outcome_unknown'&&value.status==='prepared'&&value.outcome===null&&prior.preparation&&equal(prior.preparation,value.preparation)&&prior.chunks.length===1&&prior.chunks[0].status==='unknown'&&value.chunks.length===0){
   try{const a=await receipt(d,c,p.run.run_id,s),ctl=await control(d,c,s),op=await boundOperation(d,c,p,prior,0,s),result=op?await get(d,`${workerPrefix(c)}/${p.run.run_id}/subscription-jobs/results/${op.chunk.operation_id}.json`,s):undefined,o=op?.raw.value.operation;
    retry=a.receipt.key===p.key&&activeFor(ctl,p.run.run_id)?.key===p.key&&o?.state==='unknown'&&o?.outcome_code==='evidence_not_in_source'&&(op?.spec.model==='gpt-5.6-luna'||op?.spec.model==='gpt-5.6-terra'&&((op.spec.extractor_version==='codex-subscription-extractor-v1'&&op.spec.extractor_bundle_sha256==='eb8df7c6174117aee526be567279ad005e38a21dfef5b577657390e2b0dd753e')||(op.spec.extractor_version==='codex-subscription-extractor-v2'&&op.spec.extractor_bundle_sha256==='e6ae7b7bd4d5518f65fc0f88c32ca2c2eee5ab40c081e4592314b457f2e8e7ff')))&&op?.spec.provider==='codex-chatgpt-subscription'&&result===null;
   }catch{retry=false;}
  }
  const transitions:Record<string,string[]>={prepared:['prepared','dispatching','deferred'],dispatching:['dispatching','held','complete','deferred'],held:['held','complete','deferred'],complete:[],deferred:[]};if(!equal(prior,value)&&!transitions[prior.status]?.includes(value.status)&&!resume&&!retry)fail(409,'graph_catalog_state_transition');if(prior.preparation&&!equal(prior.preparation,value.preparation))fail(409,'graph_catalog_state_transition');if(value.chunks.length<prior.chunks.length&&!retry)fail(409,'graph_catalog_state_transition');if(!retry)for(let n=0;n<prior.chunks.length;n++)if(prior.chunks[n].operation_id!==value.chunks[n].operation_id)fail(409,'graph_catalog_state_transition');}
 for(let n=0;n<value.chunks.length;n++){const chunk=value.chunks[n];if(!exact(chunk,['chunk_ordinal','operation_id','status','receipt_sha256'])||chunk.chunk_ordinal!==n||!/^subop_[a-f0-9]{64}$/.test(chunk.operation_id)||!SHA.test(chunk.receipt_sha256)||!['complete','paused','unknown','denied','cancelled'].includes(chunk.status))fail(400,'graph_catalog_state_invalid');}
 if(value.outcome!==null){const o=value.outcome,fields=['status','code','receipt_sha256','run_id','document_ordinal','recorded_at','chunk_receipts_sha256',...(value.status==='complete'?['completed_chunks']:[]),...(o?.reconciliation_evidence_sha256===undefined?[]:['reconciliation_evidence_sha256']),...(o?.code==='pre_dispatch_failure'?['cause_code']:[])];
  const codes:Record<string,string[]>={complete:['document_canary_complete'],deferred:['missing_text','oversize','invalid_utf8','source_changed','preparation_oversize','review_declined'],held:['subscription_limit_pause','subscription_login_required','dispatch_outcome_unknown','source_not_authorized','pre_dispatch_failure']};
  const causes=['cancelled','controller_cancelled','controller_conflict','controller_preparation_changed','controller_preparation_invalid','gateway_authorization_denied','gateway_control_unknown','gateway_deadline','gateway_response_invalid','gateway_text_response_invalid','gateway_text_unknown','gateway_transport_unknown','source_not_authorized','worker_configuration','worker_manifest_invalid','worker_source_changed','worker_preparation_unknown'];
  if(!exact(o,fields)||o.status!==value.status||!codes[value.status]?.includes(o.code)||(o.code==='pre_dispatch_failure'&&!causes.includes(o.cause_code))||!SHA.test(o.receipt_sha256)||o.run_id!==p.run.run_id||o.document_ordinal!==0||o.chunk_receipts_sha256!==hash(canonical(value.chunks))||typeof o.recorded_at!=='string'||!Number.isFinite(Date.parse(o.recorded_at))||(o.reconciliation_evidence_sha256!==undefined&&!SHA.test(o.reconciliation_evidence_sha256))||(value.status==='complete'&&o.completed_chunks!==value.chunks.length))fail(400,'graph_catalog_state_invalid');
 }else if(['complete','deferred','held'].includes(value.status))fail(400,'graph_catalog_state_invalid');
 if(value.preparation&&!await preparation(d,c,p,value,s))fail(409,'graph_catalog_preparation_unconfirmed');
 if(value.status==='complete'&&(value.chunks.some((x:any)=>x.status!=='complete')||!await completed(d,c,p,value,s)))fail(409,'graph_catalog_completion_unconfirmed');
}
export async function resolveCatalogCohortBinding(ctx:AuthContext,runId:string,signal:AbortSignal,i?:Partial<GraphCatalogDeps>):Promise<{cohort_id:string;source_policy:{catalog_key:string;catalog_source_sha256:string;source_prefixes:string[];source_scope?:'all_cfo_source_documents'};policy:{schema:'graph-worker-bindings-v1';policy_version:string;expires_at:string;bindings:Binding[]};binding:Binding}|null>{
 if(!ctx.connector_surface)return null;const d=depsOf(i);let all;try{all=JSON.parse(d.configs());}catch{return null;}if(!Array.isArray(all)||all.length>32)return null;
 for(const raw of all){const c=configFor(d.configs(),raw?.cohort_id);if(!c||!live(c,d))continue;const profile=deployment(c);if(ctx.caller_agent!==profile.scope.authenticatedCaller)continue;const ctl=await control(d,c,signal),active=activeFor(ctl,runId);if(!active)continue;const a=await receipt(d,c,runId,signal);if(a.receipt.key!==active.key||a.receipt.manifest_sha256!==active.manifest_sha256)fail();const binding:Binding={authenticated_caller:profile.scope.authenticatedCaller,run:a.proposal.run,room:profile.scope.room,source_index:profile.scope.sourceIndex},source_policy={catalog_key:c.catalog_key,catalog_source_sha256:c.catalog_source_sha256,source_prefixes:c.source_prefixes,...(c.source_scope?{source_scope:c.source_scope}:{})};return{cohort_id:c.cohort_id,source_policy,binding,policy:{schema:'graph-worker-bindings-v1',policy_version:c.policy_sha256,expires_at:c.expires_at,bindings:[binding]}};}return null;
}
export function registerGraphCatalogControllerRoutes(app:FastifyInstance,i?:Partial<GraphCatalogDeps>):void{
 const d=depsOf(i),prefix='/graph-catalog/v1/:cohortId';
 const route=(method:'GET'|'POST'|'PUT',suffix:string,fn:(r:FastifyRequest,p:FastifyReply,c:Cfg,s:AbortSignal)=>Promise<any>,recovery=false)=>{
 app.route({method,url:prefix+suffix,bodyLimit:256*1024,handler:async(r,p)=>{const internal=new AbortController(),timer=setTimeout(()=>internal.abort(),45000);const cancel=()=>internal.abort();r.raw.on('aborted',cancel);const disconnected=()=>{if(!p.raw.writableFinished)cancel();};p.raw.on('close',disconnected);
 try{if(r.url.includes('?')||typeof r.headers.authorization!=='string')fail(403,'graph_catalog_forbidden');const ctx=await bounded(()=>d.authenticate(r,p),internal.signal);if(p.sent)return;if(!ctx?.connector_surface)fail(403,'graph_catalog_forbidden');const c=configFor(d.configs(),(r.params as Json).cohortId);if(!c)fail(404,'graph_catalog_disabled');if(ctx.caller_agent!==deployment(c).scope.authenticatedCaller)fail(403,'graph_catalog_forbidden');if(recovery?!recoveryLive(c,d):suffix==='/state/*'?!live(c,d)&&!recoveryLive(c,d):suffix!=='/config'&&!live(c,d))fail(403,'graph_catalog_disabled');return await fn(r,p,c,internal.signal);}
 catch(e:any){if(!p.sent)return p.code(Number.isInteger(e?.status)?e.status:503).send({error:typeof e?.code==='string'&&e.code.startsWith('graph_catalog_')?e.code:'graph_catalog_unavailable'});}
 finally{clearTimeout(timer);internal.abort();r.raw.off('aborted',cancel);p.raw.off('close',disconnected);}}});};
 route('GET','/config',async(_r,_p,c)=>({enabled:live(c,d),cohort_id:c.cohort_id,controller:{catalogSourceSha256:c.catalog_source_sha256,purpose:c.purpose,runVersion:c.run_version,batchSize:c.batch_size},policy_sha256:c.policy_sha256,max_admissions:c.max_admissions,...(c.max_active_admissions===1?{}:{max_active_admissions:c.max_active_admissions})}));
 route('POST','/page',async(r,_p,c,s)=>{const b=r.body as Json;if(!exact(b,['cursor','limit'])||!Number.isInteger(b.limit)||b.limit<1||b.limit>c.batch_size)fail(400,'graph_catalog_request_invalid');return planGraphCatalogPage({...await catalog(d,c,s),scope:deployment(c).scope,cursor:b.cursor,limit:b.limit});});
 route('POST','/target-page',async(r,_p,c,s)=>{const b=r.body as Json;if(!exact(b,['source_document_version','catalog_source_sha256'])||!/^docv_[a-f0-9]{64}$/.test(b.source_document_version)||!SHA.test(b.catalog_source_sha256))fail(400,'graph_catalog_request_invalid');const cat=await catalog(d,c,s);for(const row of cat.rows){const page=planGraphCatalogPage({...cat,scope:deployment(c).scope,rows:[row],limit:1}),item=page.page.manifest?.documents[0];if(item&&item.document_version_id===b.source_document_version&&item.source_version===b.catalog_source_sha256)return{catalog:page.catalog,page:{...page.page,next_cursor:null,done:true},cursor_reset:false};}fail(409,'graph_catalog_target_missing');});
 route('POST','/target-proposal',async(r,_p,c,s)=>{const b=r.body as Json;if(!exact(b,['source_document_version','catalog_source_sha256'])||!/^docv_[a-f0-9]{64}$/.test(b.source_document_version)||!SHA.test(b.catalog_source_sha256))fail(400,'graph_catalog_request_invalid');const cat=await catalog(d,c,s);for(const row of cat.rows){const page=planGraphCatalogPage({...cat,scope:deployment(c).scope,rows:[row],limit:1}),manifest=page.page.manifest,item=manifest?.documents[0];if(!item||!manifest||item.document_version_id!==b.source_document_version||item.source_version!==b.catalog_source_sha256)continue;const p=proposal(c,cat,manifest,'targeted-promotion'),profile=deployment(c);await immutable(d,sourceSnapshotRowKey(c,item),{schema:'catalog-mention-snapshot-v1',room:profile.scope.room,document_version_id:item.document_version_id,row:page.page.rows[0]},s);await immutable(d,sourceSnapshotManifestKey(c,manifest),manifest,s);await immutable(d,path(c,`server/proposals/${p.key}.json`),p,s);await immutable(d,path(c,`server/targeted-manifests/${p.key}.json`),{key:p.key,manifest},s);return{confirmed:true,proposal:p};}fail(409,'graph_catalog_target_missing');});
 route('POST','/promotion-complete',async(r,_p,c,s)=>{const b=r.body as Json;if(!exact(b,['key','run_id','artifact_ref','producer_id','parent_run','parent_artifact_ref','source_refs','source_refs_sha256'])||!SHA.test(b.key)||!/^run_[a-f0-9]{64}$/.test(b.run_id))fail(400,'graph_catalog_request_invalid');const p=await serverProposal(d,c,b.key,s),input=promotionInput(c,p,b);if(!input)fail(409,'graph_catalog_promotion_invalid');const admitted=await receipt(d,c,p.run.run_id,s),ctl=await control(d,c,s),active=activeFor(ctl,p.run.run_id);if(admitted.receipt.key!==p.key||active?.key!==p.key)fail(403,'graph_catalog_promotion_forbidden');const grant=await get(d,`${deployment(c).publicationPrefix}/${c.cohort_id}/${input.producer_id}/runs/${p.run.run_id}.json`,s);if(!grant||!publicationGrant(grant.value,c,p,input))fail(409,'graph_catalog_publication_missing');const lineage={schema:'graph-catalog-promotion-lineage-v1',...input};await immutable(d,path(c,`server/promotion-lineages/${p.key}.json`),lineage,s);const completion={schema:'graph-catalog-promotion-completion-v1',key:p.key,run_id:p.run.run_id,artifact_ref:input.artifact_ref,parent_run:input.parent_run,parent_artifact_ref:input.parent_artifact_ref,source_refs:input.source_refs,source_refs_sha256:input.source_refs_sha256,lineage_sha256:hash(canonical(lineage)),publication_grant_sha256:hash(grant.raw.body)};await immutable(d,path(c,`server/promotion-completions/${p.key}.json`),completion,s);return{confirmed:true,key:p.key,run_id:p.run.run_id,completion_sha256:hash(canonical(completion))};});
 route('POST','/source-current',async(r,_p,c,s)=>{const b=r.body as Json;if(!exact(b,['item'])||!validItem(b.item,c))fail(400,'graph_catalog_request_invalid');return{current:await current(d,c,b.item,s)};});
 route('POST','/publish',async(r,_p,c,s)=>{const b=r.body as Json;if(!exact(b,['manifest','rows'])||!validManifest(b.manifest,c)||!Array.isArray(b.rows)||b.rows.length!==1)fail(400,'graph_catalog_request_invalid');const cat=await catalog(d,c,s),item=b.manifest.documents[0];let found=false;
 for(const row of cat.rows){if(hash(String(row.path))!==item.source_path_hash)continue;const planned=planGraphCatalogPage({...cat,scope:deployment(c).scope,rows:[row],limit:1});if(equal(planned.page.manifest,b.manifest)&&equal(planned.page.rows,b.rows)){found=true;break;}}if(!found)fail(409,'graph_catalog_source_changed');
 const p=proposal(c,cat,b.manifest),profile=deployment(c);await immutable(d,sourceSnapshotRowKey(c,item),{schema:'catalog-mention-snapshot-v1',room:profile.scope.room,document_version_id:item.document_version_id,row:b.rows[0]},s);await immutable(d,sourceSnapshotManifestKey(c,b.manifest),b.manifest,s);await immutable(d,path(c,`server/proposals/${p.key}.json`),p,s);await immutable(d,path(c,`server/manifests/${b.manifest.manifest_sha256}.json`),{key:p.key,manifest:b.manifest},s);return{confirmed:true,manifest_sha256:b.manifest.manifest_sha256,documents:1};});
 route('GET','/manifests/:sha',async(r,_p,c,s)=>{const sha=(r.params as Json).sha;if(!SHA.test(sha))fail(400,'graph_catalog_request_invalid');const saved=await get(d,path(c,`server/manifests/${sha}.json`),s)??await get(d,sourceSnapshotManifestKey(c,{manifest_sha256:sha}),s),manifest=saved?.value?.manifest??saved?.value;if(!manifest||!validManifest(manifest,c)||manifest.manifest_sha256!==sha)fail(404,'graph_catalog_manifest_missing');return manifest;});
 route('GET','/state/*',async(r,p,c,s)=>{const key=(r.params as Json)['*'];if(!/^(cursor|versions\/[a-f0-9]{64})$/.test(key))fail(400,'graph_catalog_request_invalid');const v=await get(d,path(c,`controller/${key}.json`),s);if(!v)return p.code(404).send({error:'graph_catalog_state_missing'});return{revision:v.etag,value:v.value};});
 route('PUT','/state/*',async(r,p,c,s)=>{const key=(r.params as Json)['*'],b=r.body as Json;if(!/^(cursor|versions\/[a-f0-9]{64})$/.test(key)||!exact(b,['key','revision','value'])||b.key!==key||!(b.revision===null||ETAG.test(b.revision)))fail(400,'graph_catalog_request_invalid');const old=await get(d,path(c,`controller/${key}.json`),s);if((old?.etag??null)!==b.revision)return p.code(409).send({committed:false});if(!live(c,d)){if(key==='cursor'||!old||!['dispatching','held'].includes(old.value.status)||b.value?.status!=='complete'||!equal(old.value.proposal,b.value.proposal))fail(403,'graph_catalog_recovery_forbidden');await receipt(d,c,old.value.proposal.run.run_id,s);}await validateState(d,c,key,b.value,old?.value??null,s);if(!await cas(d,path(c,`controller/${key}.json`),old,b.value,s))return p.code(409).send({committed:false});const saved=await get(d,path(c,`controller/${key}.json`),s);if(!saved||!equal(saved.value,b.value))fail();return{committed:true,revision:saved.etag};});
 route('POST','/admit',async(r,_p,c,s)=>{const b=r.body as Json;if(!exact(b,['key','manifest_sha256'])||!SHA.test(b.key)||!SHA.test(b.manifest_sha256))fail(400,'graph_catalog_request_invalid');const p=await serverProposal(d,c,b.key,s);if(p.manifest.manifest_sha256!==b.manifest_sha256)fail(409,'graph_catalog_proposal_missing');let ctl=await control(d,c,s),entry=ctl?.entries.find(v=>v.key===b.key);
 if(entry?.status==='active'){if(!await current(d,c,p.manifest.documents[0],s))fail(409,'graph_catalog_source_changed');return(await receipt(d,c,p.run.run_id,s)).receipt;}
 if(!entry){if(!await current(d,c,p.manifest.documents[0],s))fail(409,'graph_catalog_source_changed');const retained:ControlEntry[]=[];for(const active of ctl?.entries??[]){if(active.status==='reserved'){retained.push(active);continue;}const prior=await receipt(d,c,active.run_id,s),progress=await get(d,path(c,`controller/versions/${prior.proposal.key}.json`),s);if(!progress||!await settled(d,c,prior.proposal,progress.value,s))retained.push(active);}if(retained.length>=c.max_active_admissions)fail(409,'graph_catalog_active_capacity');if((ctl?.value.used??0)>=c.max_admissions)fail(409,'graph_catalog_budget_exhausted');const reserved=controlV2(c,(ctl?.value.used??0)+1,[...retained,{status:'reserved',key:b.key,run_id:p.run.run_id,manifest_sha256:b.manifest_sha256}]);if(!await cas(d,path(c,'server/control.json'),ctl,reserved,s))fail(409,'graph_catalog_admission_conflict');ctl=await control(d,c,s);entry=ctl?.entries.find(v=>v.key===b.key);}
 if(!ctl||entry?.status!=='reserved')fail();if(!live(c,d))fail(403,'graph_catalog_disabled');
 const state={status:'active',run:p.run,superseded_run:null,tombstone:null};await immutable(d,`${workerPrefix(c)}/${p.run.run_id}/active-runs/${hash(canonical({purpose:c.purpose,scope:deployment(c).scope.scope}))}.json`,{schema:'neptune-trial-active-run-state-v1',state_sha256:hash(canonical(state)),state},s);
 const unsigned={allowed:true,key:b.key,run_id:p.run.run_id,manifest_sha256:b.manifest_sha256,max_documents:1,policy_sha256:c.policy_sha256},issued={...unsigned,decision_sha256:hash(canonical(unsigned))};await immutable(d,path(c,`server/admissions/${p.run.run_id}.json`),issued,s);
 const active=controlV2(c,ctl.value.used,ctl.entries.map(v=>v.key===b.key?{...v,status:'active'}:v));if(!live(c,d)||!await cas(d,path(c,'server/control.json'),ctl,active,s))fail(409,'graph_catalog_admission_conflict');return issued;
 });
 route('POST','/review',async(r,_p,c,s)=>{const b=r.body as Json;if(!exact(b,['key','run_id','manifest_sha256']))fail(400,'graph_catalog_request_invalid');const a=await receipt(d,c,b.run_id,s),active=activeFor(await control(d,c,s),b.run_id);if(a.receipt.key!==b.key||a.receipt.manifest_sha256!==b.manifest_sha256||active?.key!==b.key)fail(403,'graph_catalog_review_forbidden');return a.receipt;});
 route('POST','/recovery',async(r,_p,c,s)=>{const b=r.body as Json;if(!exact(b,['key','run_id']))fail(400,'graph_catalog_request_invalid');const a=await receipt(d,c,b.run_id,s),active=activeFor(await control(d,c,s),b.run_id);if(a.receipt.key!==b.key||active?.key!==b.key)fail(403,'graph_catalog_recovery_forbidden');const v={allowed:true,key:b.key,run_id:b.run_id,policy_sha256:c.recovery_policy_sha256};return{...v,decision_sha256:hash(canonical(v))};},true);
 route('GET','/recovery-state/:runId/:artifact/:operationId.json',async(r,p,c,s)=>{const q=r.params as Json;if(!['operations','results'].includes(q.artifact)||!/^subop_[a-f0-9]{64}$/.test(q.operationId))fail(400,'graph_catalog_request_invalid');const a=await receipt(d,c,q.runId,s),active=activeFor(await control(d,c,s),q.runId),progress=await get(d,path(c,`controller/versions/${a.proposal.key}.json`),s),n=progress?.value.chunks?.findIndex((v:any)=>v.operation_id===q.operationId);if(active?.key!==a.receipt.key||!progress||!Number.isInteger(n)||n<0)fail(403,'graph_catalog_recovery_forbidden');const op=await boundOperation(d,c,a.proposal,progress.value,n,s);if(!op)fail(403,'graph_catalog_recovery_forbidden');const saved=q.artifact==='operations'?op.raw:await resultFor(d,c,a.proposal,op,s);if(!saved)return p.code(404).send({error:'graph_catalog_result_missing'});p.header('etag',saved.etag).type('application/json');return p.send(saved.raw.body);},true);
}
export const graphCatalogControllerTest={canonical,hash,configFor,validManifest,validItem,BASE,controllerId,proposal};




/** Resolve only already-issued server records. This never admits or reopens a run. */
export async function resolveRelationshipPublicationAdmission(input:{cohortId:string;run:{run_id:string};ctx:AuthContext;signal:AbortSignal},injected?:Partial<GraphCatalogDeps>){
 const {cohortId,run,ctx,signal}=input;
 if(!ctx.connector_surface||!SHA.test(ctx.caller_hash)||!ID.test(cohortId)||!validPath(cohortId)||!/^run_[a-f0-9]{64}$/.test(run.run_id))fail(403);
 const d=depsOf(injected),c=configFor(d.configs(),cohortId);if(!c||ctx.caller_agent!==deployment(c).scope.authenticatedCaller)fail(403);
 const admissionKey=`${BASE}/${cohortId}/server/admissions/${run.run_id}.json`;
 const admission=await get(d,admissionKey,signal);if(!admission||!SHA.test(admission.value.key))fail(403);
 const proposalKey=`${BASE}/${cohortId}/server/proposals/${admission.value.key}.json`,proposal=await get(d,proposalKey,signal);if(!proposal)fail(403);
 if(!validManifest(proposal.value.manifest,c)||proposal.value.run?.run_id!==run.run_id||proposal.value.run?.scope!==deployment(c).scope.scope)fail(403);
 const pin=(key:string,r:NonNullable<typeof admission>)=>{const version_id=r.raw.headers.get('x-amz-version-id');if(!version_id||version_id==='null'||version_id.length>1024||/[\s\p{C}]/u.test(version_id))fail();return{key,version_id,sha256:hash(r.raw.body)};};
 return{admission:pin(admissionKey,admission),proposal:pin(proposalKey,proposal)};
}
