import assert from 'node:assert/strict';
import test from 'node:test';
import { generateKeyPairSync, sign, createHash } from 'node:crypto';
import { createIdentityRegistrySourceAuthority } from './identity-registry-source-authority.js';
const canonical=(v:any):string=>v===null||typeof v!=='object'?JSON.stringify(v):Array.isArray(v)?'['+v.map(canonical).join(',')+']':'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}';
const h=(v:any)=>createHash('sha256').update(typeof v==='string'?v:canonical(v)).digest('hex');
const authority={schema:'authenticated-structured-identity-authority-v1' as const,adapter_id:'source-owner',source_system:'ledger',scope:'cfo' as const,version:'v1'};
const runContent={ref_version:'neptune-trial-active-run-ref-v1',purpose:'graph',scope:'finance',run_version:'v1',manifest_sha256:'a'.repeat(64)};
const run={...runContent,run_id:'run_'+h(runContent)};
function fixture(mode='ok'){
 const keys=generateKeyPairSync('ed25519'),publicKey=keys.publicKey.export({type:'spki',format:'pem'}).toString(),keyHash=h(keys.publicKey.export({type:'spki',format:'der'})); const catalog={catalog_version:'catalog-v1',catalog_sha256:'b'.repeat(64)},partitionManifestVersion='sirm_'+'c'.repeat(64),pagePin={cursor:null,key:'exports/pages/0',version_id:'page-v1',sha256:h('page')},coveragePin={cursor:null,key:'exports/coverage/0',version_id:'coverage-v1',sha256:h('coverage')},shardPin={shard_id:'s0',key:'exports/shards/s0',version_id:'shard-v1',sha256:h('shard'),registry_version:'rv1',source_version:'source-v1'};
 const unsigned={registry_id:'cfo-registry',source_authority:authority,run,catalog,partition_manifest_version:partitionManifestVersion,source_generation:'g1',pages:[{...pagePin,source_version:'source-v1'}],coverage_pages:[{...coveragePin,source_version:'source-v1'}],shards:[shardPin],public_key_sha256:keyHash}; const manifest={snapshot:{schema:'source-identity-registry-explicit-export-manifest-v1',...unsigned,version:'siex_'+h(unsigned)},signature:''}; const signed=(snapshot:any)=>({snapshot,signature:sign(null,Buffer.from(canonical(snapshot)),keys.privateKey).toString('base64')}); manifest.signature=signed(manifest.snapshot).signature;
 let pointer=signed({schema:'source-identity-registry-explicit-export-current-v1',registry_id:'cfo-registry',manifest_version:manifest.snapshot.version,source_generation:'g1',expires_at:'2030-01-01T00:00:00.000Z',revoked:false}); const values=new Map<string,any>([[`manifest@manifest-v1@${h('manifest')}`,manifest],[`exports/pages/0@page-v1@${pagePin.sha256}`,{schema:'structured-identity-source-page-v1',authority,current:true,source_version:'source-v1',records:[],next_cursor:null}],[`exports/coverage/0@coverage-v1@${coveragePin.sha256}`,{schema:'source-identity-catalog-coverage-page-v1',source_generation:'g1',catalog_version:catalog.catalog_version,coverage_sha256:catalog.catalog_sha256,binding_hashes:['d'.repeat(64)],next_cursor:null}]]);
 let reads=0; const readJson=async(r:any,{signal}:any)=>{reads++;if(mode==='hang')return await new Promise<any>(()=>{});if(r.key==='pointer'){if(mode==='missing')throw Error('missing');return {value:mode==='expired'?signed({...pointer.snapshot,expires_at:'2020-01-01T00:00:00.000Z'}):mode==='revoked'?signed({...pointer.snapshot,revoked:true}):pointer,version_id:'pointer-v1'};}const value=values.get(`${r.key}@${r.version_id}@${r.sha256}`);if(!value)throw Error('missing');if(mode==='flip'&&r.key==='exports/pages/0')pointer=signed({...pointer.snapshot,source_generation:'g2'});return {value:mode==='bad-signature'?{...value,signature:'bad'}:value,version_id:mode==='bad-version'?'other':r.version_id};};
 const api=createIdentityRegistrySourceAuthority({registryId:'cfo-registry',authority,run,catalog,partitionManifestVersion,publicKey,manifest:{key:'manifest',version_id:'manifest-v1',sha256:h('manifest')},pointer:{key:'pointer'},readJson,now:()=>Date.parse('2026-09-09T00:00:00.000Z'),timeoutMs:100}); return {api,reads,shardPin,catalog,partitionManifestVersion};
}
test('reads only signed pinned explicit source pages and coverage',async()=>{const f=fixture();const page=await f.api.source.page({cursor:null,source_version:null,page_size:100});assert.equal(page.schema,'structured-identity-source-page-v1');assert.equal(await f.api.source.current({source_version:'source-v1'}),true);assert.equal(await f.api.partitions.manifest_current({registry_id:'cfo-registry',manifest_version:f.partitionManifestVersion,source_generation:'g1'}),true);assert.equal(await f.api.partitions.shard_current({registry_id:'cfo-registry',manifest_version:f.partitionManifestVersion,shard_id:'s0',registry_version:'rv1',source_version:'source-v1'}),true);assert.equal(await f.api.partitions.binding_covered({registry_id:'cfo-registry',manifest_version:f.partitionManifestVersion,source_generation:'g1',catalog_version:f.catalog.catalog_version,coverage_sha256:f.catalog.catalog_sha256,source_binding_hash:'d'.repeat(64)}),true);});
for(const mode of ['missing','expired','revoked','flip','bad-signature','bad-version'])test(`fails closed for ${mode}`,async()=>{const f=fixture(mode);await assert.rejects(f.api.source.page({cursor:null,source_version:null,page_size:100}));});
test('bounds an ignored-signal reader',async()=>{const f=fixture('hang');const before=Date.now();await assert.rejects(f.api.source.page({cursor:null,source_version:null,page_size:100}),{code:'identity_source_authority_deadline'});assert.ok(Date.now()-before<1000);});
