import { createHash } from 'node:crypto';
import { canonicalQueryString, canonicalUri, resolveAwsCredentials, signRequest, type AwsCredentials, type SignedRequest } from '../search/sigv4.js';

const BUCKET='otchealth-finance-legal-dr-55c84f6b', REGION='us-east-1', ROOT='graph-trial/20260908/relationship-publications/cfo';
const MAX=128*1024, DEADLINE=15_000, RUN=/^run_[a-f0-9]{64}$/, LABEL=/^[a-z][a-z0-9-]{0,63}$/;
export type PublicationRecord={runId:string;body:Buffer;versionId?:string};
export type PublicationRead={found:false}|{found:true;body:Buffer;versionId:string};
export type PublicationList={records:PublicationRecord[];next?:string};
export interface RelationshipPublicationStoreDeps { cohort:string; producer:string; callerAgent?:'cfo'|'clo'; resolveCredentials?:()=>Promise<AwsCredentials|null>; signRequest?: (o:Parameters<typeof signRequest>[0])=>SignedRequest; fetch?:typeof globalThis.fetch; now?:()=>number; }
export interface RelationshipPublicationStore { get(runId:string,signal:AbortSignal):Promise<PublicationRead>; putCreateOnly(record:PublicationRecord,signal:AbortSignal):Promise<PublicationRead>; list(input:{after?:string;limit:number;signal:AbortSignal}):Promise<PublicationList>; }
const hash=(b:Buffer)=>createHash('sha256').update(b).digest('hex');
function storeError(code:string,upstreamStatus?:number){return Object.assign(Error(code),{code,publicationStoreError:true,...(upstreamStatus===undefined?{}:{upstreamStatus})});}
function label(v:string){return LABEL.test(v)&&v!=='.'&&v!=='..';}
function body(v:Buffer){if(!Buffer.isBuffer(v)||v.length<2||v.length>MAX||!Buffer.from(v.toString('utf8')).equals(v))throw Error('record');let parsed:unknown;try{parsed=JSON.parse(v.toString('utf8'));}catch{throw Error('record');}if(!parsed||Object.getPrototypeOf(parsed)!==Object.prototype)throw Error('record');}
function bound(v:number){if(!Number.isSafeInteger(v)||v<1||v>64)throw Error('limit');}
function key(prefix:string,run:string){if(!RUN.test(run))throw Error('run');return `${prefix}runs/${run}.json`;}
function contentLength(h:Headers){const x=h.get('content-length');if(x===null)return null;if(!/^\d+$/.test(x))throw Error('size');const n=Number(x);if(!Number.isSafeInteger(n))throw Error('size');return n;}
async function cancel(r:ReadableStreamDefaultReader<Uint8Array>){await Promise.race([r.cancel().catch(()=>undefined),new Promise<void>(ok=>setTimeout(ok,100))]);}
async function read(r:Response,max:number,s:AbortSignal){const declared=contentLength(r.headers);if(declared!==null&&declared>max){if(r.body)await cancel(r.body.getReader());throw Error('size');}if(!r.body)return Buffer.alloc(0);const reader=r.body.getReader(),chunks:Buffer[]=[];let size=0;try{for(;;){if(s.aborted)throw Error('deadline');const n=await race(reader.read(),s);if(n.done)break;size+=n.value.byteLength;if(size>max)throw Error('size');chunks.push(Buffer.from(n.value));}}catch(e){await cancel(reader);throw e;}if(declared!==null&&declared!==size)throw Error('size');return Buffer.concat(chunks,size);}
async function race<T>(p:Promise<T>,s:AbortSignal){if(s.aborted)throw Error('deadline');return await new Promise<T>((ok,bad)=>{const a=()=>bad(Error('deadline'));s.addEventListener('abort',a,{once:true});p.then(ok,bad).finally(()=>s.removeEventListener('abort',a));});}
function deadline(source:AbortSignal,now:()=>number){const c=new AbortController(),a=()=>c.abort();if(source.aborted)a();else source.addEventListener('abort',a,{once:true});const t=setTimeout(a,Math.max(0,now()+DEADLINE-now()));return{signal:c.signal,done:()=>{clearTimeout(t);source.removeEventListener('abort',a);}};}
function xmlText(text:string,tag:string){const m=text.match(new RegExp(`<${tag}>([^<]*)</${tag}>`));return m?.[1];}
function xmlDecode(v:string){if(/&(?!amp;|lt;|gt;|quot;|apos;)/.test(v))throw Error('xml');const entities:Record<string,string>={amp:'&',lt:'<',gt:'>',quot:'"',apos:"'"};return v.replace(/&(amp|lt|gt|quot|apos);/g,(_match,name:string)=>entities[name]!);}
function listKeys(xml:string,prefix:string){xml=xml.replace(/^\s*<\?xml version="1\.0" encoding="UTF-8"\?>\s*/,'');if(xml.length>MAX||/<!|<\?/.test(xml)||!/^\s*<ListBucketResult(?:\s[^>]*)?>[\s\S]*<\/ListBucketResult>\s*$/.test(xml))throw Error('xml');const keys:string[]=[];for(const m of xml.matchAll(/<Contents>([\s\S]*?)<\/Contents>/g)){const k=xmlText(m[1],'Key');if(!k)throw Error('xml');const decoded=xmlDecode(k);if(!decoded.startsWith(prefix)||!RUN.test(decoded.slice(prefix.length,-5))||!decoded.endsWith('.json'))throw Error('xml');keys.push(decoded);}if(new Set(keys).size!==keys.length||keys.some((k,i)=>i>0&&keys[i-1]!>=k))throw Error('xml');return keys;}
export function createRelationshipPublicationStore(deps:RelationshipPublicationStoreDeps):RelationshipPublicationStore {
 if(!label(deps.cohort)||!label(deps.producer)||!['cfo','clo'].includes(deps.callerAgent??'cfo'))throw Error('namespace');
 const root=deps.callerAgent==='clo'?'graph-trial/20260912/relationship-publications/clo':ROOT;
 const prefix=`${root}/${deps.cohort}/${deps.producer}/`,creds=deps.resolveCredentials??resolveAwsCredentials,sign=deps.signRequest??signRequest,fetcher=deps.fetch??fetch,now=deps.now??Date.now;
 const request=async(method:'GET'|'PUT',path:string,signal:AbortSignal,bodyValue?:Buffer,query?:Record<string,string>)=>{const d=deadline(signal,now);try{if(d.signal.aborted)throw Error('deadline');const c=await race(creds(),d.signal);if(!c)throw Error('credentials');const host=`${BUCKET}.s3.${REGION}.amazonaws.com`,extra:Record<string,string>={'x-amz-content-sha256':hash(bodyValue??Buffer.alloc(0))};if(method==='PUT'){extra['if-none-match']='*';extra['x-amz-server-side-encryption']='AES256';extra['content-type']='application/json';}const signed=sign({method,host,path,query,region:REGION,service:'s3',credentials:c,...(bodyValue?{body:bodyValue}:{}),extraHeaders:extra});const response=await race(fetcher(`https://${host}${canonicalUri(path)}${query?'?'+canonicalQueryString(query):''}`,{method,headers:signed.headers,...(bodyValue?{body:bodyValue as never}:{}),signal:d.signal,redirect:'error'}),d.signal);const bytes=await read(response,MAX,d.signal);return{status:response.status,headers:response.headers,body:bytes};}finally{d.done();}};
 return {
  async get(runId,signal){if(signal.aborted)throw Error('deadline');const r=await request('GET','/'+key(prefix,runId),signal);if(r.status===404)return{found:false};if(r.status!==200)throw storeError('get',r.status);const b=r.body,v=r.headers.get('x-amz-version-id');if(!v||v.length>1024||v==='null'||/\s|\p{C}/u.test(v)||r.headers.get('x-amz-server-side-encryption')!=='AES256')throw storeError('get');body(b);return{found:true,body:b,versionId:v};},
  async putCreateOnly(record,signal){body(record.body);const k=key(prefix,record.runId);const r=await request('PUT','/'+k,signal,record.body);if(r.status===200||r.status===201){const saved=await this.get(record.runId,signal);if(!saved.found||!saved.body||!saved.body.equals(record.body))throw Error('verify');return saved;}if(r.status===409||r.status===412){const saved=await this.get(record.runId,signal);if(saved.found&&saved.body?.equals(record.body))return saved;throw Error('conflict');}throw Error('put');},
  async list({after,limit,signal}){bound(limit);if(after!==undefined&&!RUN.test(after))throw Error('cursor');const runs=`${prefix}runs/`,query:Record<string,string>={'list-type':'2','max-keys':String(limit+1),prefix:runs};if(after)query['start-after']=key(prefix,after);const r=await request('GET','/',signal,undefined,query);if(r.status!==200)throw Error('list');const xml=r.body.toString('utf8'),keys=listKeys(xml,runs);if(keys.some(k=>after!==undefined&&k<=key(prefix,after))||keys.length>limit+1)throw Error('list');const truncated=xmlText(xml,'IsTruncated');if(truncated!=='true'&&truncated!=='false')throw Error('xml');if(truncated==='true'&&keys.length<=limit)throw Error('xml');const selected=keys.slice(0,limit);const records:PublicationRecord[]=[];for(const k of selected){const id=k.slice(runs.length,-5),got=await this.get(id,signal);if(!got.found)throw Error('list');records.push({runId:id,body:got.body,versionId:got.versionId});}return{records,...(keys.length>limit?{next:selected[selected.length-1]!.slice(runs.length,-5)}:{})};},
 };
}
export const relationshipPublicationStoreTest={BUCKET,REGION,ROOT,MAX,listKeys,xmlDecode};
