import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {pathToFileURL} from 'node:url';
import {join} from 'node:path';
import {createAutoPublicationFixture,loadActualRelationshipModules} from './auto-publication-fixture.mjs';
import {createHistoricalRelationshipReader} from './historical-reader.mjs';
import {createGatewayRelationshipStore} from './gateway-store.mjs';
for(const key of ['CIO_SITE_ID','CIO_TRACK_KEY','CIO_APP_API_BEARER','PERPLEXITY_CONNECTOR_TOKEN','ADMIN_REVOKE_TOKEN','N8N_WEBHOOK_SECRET'])process.env[key]??='synthetic-placeholder-value-000000000';
import test from 'node:test';
import {createCandidatePromotionPlanner,createCandidatePromotionReview,createHistoricalCandidateParentReader,createPreparedPromotionSourceRefresher,createPartitionCoverageAdapter} from './candidate-promotion.mjs';
import {createRelationshipPublicationPipeline} from './publication-pipeline.mjs';
const canonical=v=>v===null||typeof v!=='object'?JSON.stringify(v):Array.isArray(v)?'['+v.map(canonical).join(',')+']':'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}'; const hash=v=>createHash('sha256').update(canonical(v)).digest('hex');
const makeRun=(purpose,manifest)=>{const body={ref_version:'neptune-trial-active-run-ref-v1',purpose,scope:'finance',run_version:'v1',manifest_sha256:manifest};return{...body,run_id:'run_'+hash(body)}};
const parentRun=makeRun('relationship-candidates','a'.repeat(64)), targetRun=makeRun('relationship-promotion','b'.repeat(64));
const ref={schema:'relationship-resolution-artifact-ref-v1',artifact_id:'resart_'+'c'.repeat(64),bucket:'synthetic',key:'synthetic/candidate.json',payload_sha256:'c'.repeat(64),version_id:'synthetic-v1',size_bytes:1};
const source={source_document_version:'source-v1',chunk_sha256:'d'.repeat(64)};
const parent={schema:'candidate-promotion-parent-v1',artifact_ref:ref,run:parentRun,candidates:[{source_ref:source,candidate:{subject:'X',predicate:'depends_on',object:'Y'}},{source_ref:source,candidate:{subject:'Y',predicate:'depends_on',object:'Z'}}]};
function planner({changed=false,covered=true}={}){return createCandidatePromotionPlanner({readParent:async()=>structuredClone(parent),refreshSource:async()=>({run_id:targetRun.run_id,catalog_manifest_sha256:targetRun.manifest_sha256,room:'finance',source_index:'finance-cfo-source-docs',source_document_version:changed?'changed':source.source_document_version,chunk_sha256:source.chunk_sha256}),assertCovered:async()=>covered});}
test('promotion preserves immutable parent refs, creates a new run-bound review input, and is idempotent',async()=>{const p=planner(),one=await p.plan({parent_artifact_ref:ref,parent_run:parentRun,run:targetRun}),two=await p.plan({parent_artifact_ref:ref,parent_run:parentRun,run:targetRun});assert.deepEqual(one,two);assert.deepEqual(one.lineage.parent_artifact_ref,ref);assert.equal(one.lineage.target_run.run_id,targetRun.run_id);assert.equal(one.review_input.bindings.length,1);assert.equal(one.review_input.candidates.length,2);assert.equal(one.review_input.bindings[0].run_id,targetRun.run_id);assert.deepEqual(parent,{schema:'candidate-promotion-parent-v1',artifact_ref:ref,run:parentRun,candidates:[{source_ref:source,candidate:{subject:'X',predicate:'depends_on',object:'Y'}},{source_ref:source,candidate:{subject:'Y',predicate:'depends_on',object:'Z'}}]});});
test('promotion holds changed, missing, and uncovered sources before signed review',async()=>{await assert.rejects(planner({changed:true}).plan({parent_artifact_ref:ref,parent_run:parentRun,run:targetRun}),{code:'candidate_promotion_source_changed'});await assert.rejects(planner({covered:false}).plan({parent_artifact_ref:ref,parent_run:parentRun,run:targetRun}),{code:'candidate_promotion_source_uncovered'});const missing=createCandidatePromotionPlanner({readParent:async()=>({schema:'candidate-promotion-parent-v1',artifact_ref:ref,run:parentRun,candidates:[]}),refreshSource:async()=>null,assertCovered:async()=>true});await assert.rejects(missing.plan({parent_artifact_ref:ref,parent_run:parentRun,run:targetRun}),{code:'candidate_promotion_parent_invalid'});});
test('promotion calls existing signed review only with fresh, covered inputs and returns lineage',async()=>{let input;const review=createCandidatePromotionReview({planner:planner(),recordLineage:async lineage=>{assert.deepEqual(lineage.parent_artifact_ref,ref);return true},createSignedReview:async({run})=>({reviewCandidates:async v=>{assert.equal(run.run_id,targetRun.run_id);input=v;return{schema:'resolution-review-receipt-v1',artifact_ref:ref}}})});const result=await review.reviewCandidates({parent_artifact_ref:ref,parent_run:parentRun,run:targetRun});assert.equal(input.bindings[0].catalog_manifest_sha256,targetRun.manifest_sha256);assert.deepEqual(result,{schema:'resolution-review-receipt-v1',artifact_ref:ref});});
test('a promoted target run uses the existing outbox idempotently without touching the parent artifact',async()=>{
 let state=null, reviews=0, publishes=0; const identity={cohort_id:'synthetic',producer_id:'reviewer',run:targetRun};
 const outbox={async get(){return state?{identity,state,receipt:state==='intent_only'?null:{artifact_ref:ref}}:null},async createIntent(){if(state)return{created:false};state='intent_only';return{created:true}},async claimReview(){return state==='intent_only'?{claimed:true,token:'synthetic'}:{claimed:false}},async releaseReview(){return true},async createReviewed(){state='reviewed';return{created:true}},async markPublished(){state='published';return{created:true}},async pagePending(){return{items:[],next_after:null,scanned_nodes:1}}};
 const plannerValue=planner(); const pipeline=createRelationshipPublicationPipeline({cohort_id:'synthetic',producer_id:'reviewer',outbox,publisher:{publish:async()=>{publishes++;return{run:targetRun,producer_id:'reviewer',artifact_ref:ref}},retrievePage:async()=>({})},loadExtracted:async()=> (await plannerValue.plan({parent_artifact_ref:ref,parent_run:parentRun,run:targetRun})).review_input,createReview:async()=>({reviewCandidates:async()=>{reviews++;return{schema:'resolution-review-receipt-v1',artifact_ref:ref}}})});
 assert.equal((await pipeline.process({run:targetRun})).status,'complete'); assert.equal((await pipeline.process({run:targetRun})).status,'complete'); assert.deepEqual({reviews,publishes},{reviews:1,publishes:1}); assert.deepEqual(parent.artifact_ref,ref);
});

test('historical parent reader accepts only current immutable candidate events',async()=>{const record={accepted:false,candidate:{subject:'X',predicate:'depends_on',object:'Y'},evidence:{source_binding:{source_document_version:source.source_document_version,chunk_sha256:source.chunk_sha256}}};const reader=createHistoricalCandidateParentReader({reader:{readArtifact:async()=>({authority:{authenticated_gateway:true,current:true},payload:{schema:'resolution-history-v1',run:parentRun,caller_seat:'cfo',sources:[],events:[{operation:'accept',output:record}],queries:[]}})}});const actual=await reader({artifact_ref:ref,run:parentRun});assert.deepEqual(actual.candidates,[{source_ref:source,candidate:record.candidate}]);});

test('production adapters use the prepared-source factory and signed partition coverage check',async()=>{let loaded=false;const refresh=createPreparedPromotionSourceRefresher({findPreparedBinding:async()=>({opaque:'controller-produced'}),sourceAdapter:{load:async binding=>{assert.deepEqual(binding,{opaque:'controller-produced'});loaded=true;return{input:{binding:{run_id:targetRun.run_id,catalog_manifest_sha256:targetRun.manifest_sha256,room:'finance',source_index:'finance-cfo-source-docs',source_document_version:source.source_document_version,chunk_sha256:source.chunk_sha256}}}}}});assert.equal((await refresh({source_ref:source,run:targetRun})).run_id,targetRun.run_id);assert.equal(loaded,true);let request;const coverage=createPartitionCoverageAdapter({registryId:'registry-1',readiness:async input=>{request=input;return{coverage_ready:true,reason:'coverage_checked'}}});const bound={run_id:targetRun.run_id,source_document_version:source.source_document_version,chunk_sha256:source.chunk_sha256};assert.equal(await coverage(bound),true);assert.deepEqual(request,{registry_id:'registry-1',run_id:targetRun.run_id,source_binding_sha256:hash({source_document_version:source.source_document_version,source_sha256:source.chunk_sha256})});const noMatch=createPartitionCoverageAdapter({registryId:'registry-1',readiness:async()=>({coverage_ready:false,reason:'coverage_missing'})});assert.equal(await noMatch(bound),false);const nullLookup=createPartitionCoverageAdapter({registryId:'registry-1',readiness:async()=>({coverage_ready:false,reason:'coverage_not_checked'})});assert.equal(await nullLookup(bound),false);});

const actualEnabled=!!process.env.RELATIONSHIP_CANDIDATE_CTO_ROOT&&!!process.env.RELATIONSHIP_STORE_MODULE;
test('historical parent reader accepts the existing observation artifact generator shape',{skip:!actualEnabled},async()=>{const m=await loadActualRelationshipModules(),f=await createAutoPublicationFixture();try{const fixture=f.fixtures[0];f.admit(0);const store=createGatewayRelationshipStore({createS3ResolutionStore:m.createS3ResolutionStore,gatewayOrigin:'https://synthetic-history.invalid',run:fixture.state.run,producer:'synthetic-reviewer-1',sse:{algorithm:'AES256'},historyTrust:fixture.options.historyTrust,authorizeArtifact:async()=>({allowed:true}),getAuthorization:async()=> 'Bearer synthetic-history-token-value-1234',fetchImpl:f.routes.fetchImpl});const observation=await import(pathToFileURL(join(process.env.RELATIONSHIP_CANDIDATE_CTO_ROOT,'tools/neptune-trial/relationship-resolution/observation-review.mjs')).href);const review=observation.createObservationReview({resolution:{...fixture.options,store},operationStore:{getOperation:async()=>{throw Error('no model')}}}),batch=fixture.batch(),receipt=await review.reviewCandidates({bindings:batch.bindings,candidates:batch.admissions.map(a=>({source_index:a.source_index,candidate:a.input.candidate})),queries:[]});const parentReader=createHistoricalCandidateParentReader({reader:{readArtifact:async ref=>({authority:{authenticated_gateway:true,current:true},payload:await store.getArtifact(ref)})}});const parentRecord=await parentReader({artifact_ref:receipt.artifact_ref,run:fixture.state.run});assert.ok(parentRecord.candidates.length>0);assert.ok(parentRecord.candidates.every(x=>x.source_ref.chunk_sha256===x.candidate.source_sha256));}finally{await f.routes.close();}});
