import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash,generateKeyPairSync,sign} from 'node:crypto';
import {mkdtemp,rm,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {runRelationshipCatalogScheduler} from './catalog-scheduler.mjs';
import {createGatewayRelationshipStore} from './gateway-store.mjs';
import {createAutoPublicationFixture,loadActualRelationshipModules} from './auto-publication-fixture.mjs';
const canonical=v=>v===null||typeof v!=='object'?JSON.stringify(v):Array.isArray(v)?'['+v.map(canonical).join(',')+']':'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}';
const hash=v=>createHash('sha256').update(v).digest('hex');
const enabled=!!process.env.RELATIONSHIP_REVIEW_ROOT&&!!process.env.RELATIONSHIP_STORE_MODULE;
for(const [k,v]of Object.entries({CIO_SITE_ID:'synthetic',CIO_TRACK_KEY:'synthetic',CIO_APP_API_BEARER:'synthetic',PERPLEXITY_CONNECTOR_TOKEN:'synthetic-placeholder-value-000000000',ADMIN_REVOKE_TOKEN:'synthetic-placeholder-value-000000000',N8N_WEBHOOK_SECRET:'synthetic-placeholder-value-000000000'}))process.env[k]??=v;
test('actual scheduler resumes a durable candidate-only review without admission, extraction, or another model call',{skip:!enabled},async()=>{
 const root=await mkdtemp(join(tmpdir(),'relationship-scheduler-')),f=await createAutoPublicationFixture(),m=await loadActualRelationshipModules();
 try{
 const modules=await Promise.all(['catalog-controller/controller-cli.mjs','relationship-resolution/observation-review.mjs','subscription-review/registry.mjs','subscription-jobs/operation-store.mjs'].map(p=>import(pathToFileURL(join(process.env.RELATIONSHIP_REVIEW_ROOT,p)).href))),[{runCatalogControllerCli},{createObservationReview},{createSignedIdentityRegistry},{createS3SubscriptionOperationStore}]=modules;
 const {publicKey,privateKey}=generateKeyPairSync('ed25519'),snapshot={schema:'source-identity-registry-v1',registry_id:'synthetic',version:'1',entries:f.fixtures.flatMap(x=>x.state.definitions.flatMap(d=>[d.subject,d.object].map(endpoint=>({source_document_version:d.binding.source_document_version,source_sha256:d.binding.chunk_sha256,mention:endpoint.display_name,endpoint}))))},signature=sign(null,Buffer.from(canonical(snapshot)),privateKey).toString('base64');
 const registry=createSignedIdentityRegistry({publicKey:publicKey.export({type:'spki',format:'pem'}),registryId:'synthetic',version:'1',readSnapshot:async()=>({snapshot,signature})});
 let models=0,extractions=0,admissions=0,loseReviewReceipt=true,rev=0;const dispatchedModels=[],storage=new Map(),records=new Map(),opRecords=new Map(),resultRecords=new Map(),monitors=[],lines=[];
 const operationStore=createS3SubscriptionOperationStore({bucket:'synthetic-review-operations',prefix:'synthetic/review',region:'us-east-1',signRequest:async r=>({url:r.url,headers:r.headers}),fetchImpl:async(url,init)=>{const k=new URL(url).pathname,old=storage.get(k),h=new Headers(init.headers);if(init.method==='GET')return old?new Response(old.body,{headers:{etag:old.etag}}):new Response(null,{status:404});if(h.get('if-none-match')==='*'&&old||h.has('if-match')&&h.get('if-match')!==old?.etag)return new Response(null,{status:412});const etag=`"v${++rev}"`;storage.set(k,{body:init.body,etag});return new Response(null,{status:200,headers:{etag}});}});
 const fakeRun=async(_binary,args,options)=>{if(args[0]==='login')return{code:0,out:'Logged in using ChatGPT'};models++;dispatchedModels.push(args[args.indexOf('--model')+1]);const q=JSON.parse(options.input.slice(options.input.indexOf('{"request":'))),c=q.request.candidate;await writeFile(args[args.indexOf('--output-last-message')+1],JSON.stringify({request_sha256:q.request_sha256,verdict:'supported',subject_index:0,object_index:1,predicate:c.predicate,polarity:'positive',qualifications:[],evidence:{start_utf16:c.evidence_start_utf16,end_utf16:c.evidence_end_utf16,quote:c.quote},reason_code:'synthetic'}));return{code:0,out:'synthetic'};};
 const token=async()=> 'Bearer synthetic-history-token-value-1234';
 const reviewOptionsForRun=async run=>{const fixture=f.fixtures.find(x=>x.state.run.run_id===run.run_id),store=createGatewayRelationshipStore({createS3ResolutionStore:m.createS3ResolutionStore,gatewayOrigin:'https://synthetic-history.invalid',run,producer:'synthetic-reviewer-1',sse:{algorithm:'AES256'},historyTrust:fixture.options.historyTrust,authorizeArtifact:async()=>({allowed:true}),getAuthorization:token,fetchImpl:f.routes.fetchImpl});return{resolution:{...fixture.options,store,historyTrust:store.boundHistoryTrust},operationStore,registry,binary:process.execPath,run:fakeRun,env:{},model:'gpt-5.6-sol'};};
 const createSubscriptionCandidateReview=async options=>{const adapter=createObservationReview(options);return Object.freeze({...adapter,reviewCandidates:async(input,opts)=>{const receipt=await adapter.reviewCandidates(input,opts);if(loseReviewReceipt){loseReviewReceipt=false;throw Error('synthetic lost review receipt');}return receipt;}})};
 const fetchImpl=f.routes.fetchImpl;
 const pipelineContext={cohort_id:'synthetic-history',store:{read:async k=>records.get(k)},operationStoreForRun:()=>({getOperation:async k=>opRecords.get(k),getResult:async k=>resultRecords.get(k)})};
 let index=0;
 async function brokerFactory(_local,{relationshipPipelineFactory}){
  const fixture=f.fixtures[index];f.admit(index);const pins=f.state.pins[fixture.state.run.run_id],proposal=JSON.parse(Buffer.from(f.state.objects[pins.proposal.key].body,'base64')),existing=records.get('versions/'+proposal.key);
  const complete={status:'complete',outcome:{status:'complete',code:'document_canary_complete',receipt_sha256:'a'.repeat(64),run_id:proposal.run.run_id,document_ordinal:0,recorded_at:new Date().toISOString()}};
  return{relationships:relationshipPipelineFactory(pipelineContext),config:{readTrusted:async()=>({enabled:true,cohort_id:'synthetic-history',policy_sha256:'b'.repeat(64),max_admissions:10,controller:{catalogSourceSha256:f.state.publicationPolicy.bindings[0].source_policy.catalog_source_sha256,purpose:proposal.run.purpose,runVersion:proposal.run.run_version,batchSize:1}})},admit:async()=>{admissions++;return{allowed:true,key:proposal.key,run_id:proposal.run.run_id,manifest_sha256:proposal.run.manifest_sha256,max_documents:1,decision_sha256:'a'.repeat(64),policy_sha256:'b'.repeat(64)}},createController:async()=>({pendingBatch:async()=>({proposals:existing?[{...proposal,status:'complete',outcome:complete.outcome}]:[]}),prepareBatch:async()=>({proposals:[{...proposal,status:existing?'complete':'prepared',...(existing?{outcome:complete.outcome}:{})}]}),reconcile:async()=>complete,execute:async()=>{
   extractions++;const d=fixture.state.definitions[0],candidate=fixture.batch().admissions[0].input.candidate,spec={purpose:proposal.run.purpose,source_binding:d.binding,provider:'synthetic-extractor',model:'synthetic-model'},id='subop_'+hash(canonical(spec)),result={operation_id:id,spec_sha256:hash(canonical(spec)),output:{provider:spec.provider,model:spec.model,billing_route:'chatgpt_subscription',paid_fallback:false,source_sha256:d.binding.chunk_sha256,candidates:[candidate]}};opRecords.set(id,{operation:{operation_id:id,spec}});resultRecords.set(id,{result,result_sha256:hash(canonical(result))});records.set('versions/'+proposal.key,{revision:'"1"',value:{schema:'catalog-controller-version-v1',proposal,status:'complete',outcome:complete.outcome,preparation:{chunk_count:1,snapshot_id:d.binding.snapshot_id,prepared_manifest_sha256:d.binding.prepared_manifest_sha256,sidecar_content_sha256:d.binding.sidecar_content_sha256},chunks:[{chunk_ordinal:0,operation_id:id,status:'complete'}]}});return complete;}})};
 }
 const configuration={runCatalogControllerCli,createSubscriptionCandidateReview,factories:m,reviewOptionsForRun,outboxDirectory:root,publisherOptions:{gatewayOrigin:'https://synthetic-history.invalid',cohortId:'synthetic-history',producer:'synthetic-reviewer-1',historyTrust:f.fixtures[0].options.historyTrust,sse:{algorithm:'AES256'},getAuthorization:token,fetchImpl,now:()=>f.state.now},argv:['--once','--config','synthetic'],env:{CODEX_CFO_MCP_TOKEN:'synthetic-placeholder'},stdout:{write:s=>lines.push(JSON.parse(s))},load:async()=>JSON.stringify({schema:'company-catalog-controller-host-v1',seat:'cfo',binary:'C:\\Tools\\codex.exe',cohort_id:'synthetic-history'}),onMonitor:async x=>monitors.push(x),brokerFactory};
 const first=await runRelationshipCatalogScheduler(configuration);assert.equal(first.at(-1).stop,'held');assert.equal(models,0);assert.equal(extractions,1);assert.equal(admissions,1);assert.equal(Object.keys(f.state.grants).length,0);
 const resumed=await runRelationshipCatalogScheduler({...configuration,resumeCandidateOnly:true,argv:['--recover','--config','synthetic']});assert.ok(resumed.some(x=>x.event==='relationship'&&x.code==='relationship_published'));assert.equal(models,0);assert.equal(extractions,1);assert.equal(admissions,1);assert.equal(Object.keys(f.state.grants).length,1);
 index=1;await runRelationshipCatalogScheduler(configuration);index=2;await runRelationshipCatalogScheduler(configuration);assert.equal(models,0);assert.deepEqual(dispatchedModels,[]);assert.equal(extractions,3);assert.equal(Object.keys(f.state.grants).length,3);assert.ok(monitors.length>=4);assert.ok(lines.every(x=>!('records'in x)&&!('candidates'in x)));
 const result=await f.host.retrievePage(f.query);assert.equal(result.recall.answer.status,'unsupported');
 }finally{await f.routes.close();await rm(root,{recursive:true,force:true});}
});
