import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import test from 'node:test';
import {createRelationshipPublicationPipeline} from './publication-pipeline.mjs';
const canonical=v=>v===null||typeof v!=='object'?JSON.stringify(v):Array.isArray(v)?'['+v.map(canonical).join(',')+']':'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}';const sha=v=>createHash('sha256').update(v).digest('hex');
const core={ref_version:'neptune-trial-active-run-ref-v1',purpose:'relationship-candidates',scope:'finance',run_version:'synthetic-v1',manifest_sha256:'a'.repeat(64)},run={...core,run_id:'run_'+sha(canonical(core))},artifact_ref={schema:'relationship-resolution-artifact-ref-v1',artifact_id:'resart_'+'b'.repeat(64),bucket:'otchealth-finance-legal-dr-55c84f6b',key:'resolution-artifacts/sha256/bb/'+'b'.repeat(64)+'.json',payload_sha256:'b'.repeat(64),version_id:'v1',size_bytes:1};
function outbox(){let state=null,reviewed=null,resume=null;const identity={cohort_id:'synthetic',producer_id:'reviewer',run};return{async get(){return state?{identity,state,receipt:reviewed,created_at:new Date().toISOString()}:null},async createIntent(){if(state)return{created:false};state='intent_only';return{created:true}},async createReviewed(_,r){reviewed=r;state='reviewed';return{created:true}},async markPublished(){state='published';return{created:true}},async claimResume(){if(state!=='intent_only'||resume)return{claimed:false};resume='claim';return{claimed:true,token:resume}},async releaseResume(_,token){assert.equal(token,resume);resume=null;return true},async pagePending(){return{items:[],next_after:null,scanned_nodes:1}}};}
test('review happens once, outbox is reviewed before publisher, and ambiguous publish retries exact artifact without review',async()=>{const box=outbox();let reviews=0,publishes=0;const pipeline=createRelationshipPublicationPipeline({cohort_id:'synthetic',producer_id:'reviewer',outbox:box,loadExtracted:async()=>({}),createReview:async()=>({reviewCandidates:async()=>{reviews++;return{schema:'resolution-review-receipt-v1',artifact_ref}}}),publisher:{async publish(v){publishes++;assert.equal((await box.get()).state,'reviewed');if(publishes===1)throw Error('ambiguous');return{run,producer_id:'reviewer',artifact_ref}},retrievePage:async()=>({})}});assert.equal((await pipeline.process({run})).status,'unknown');assert.equal(reviews,1);assert.equal((await pipeline.process({run})).status,'complete');assert.equal(reviews,1);assert.equal(publishes,2);});
test('intent-only recovery holds without review and cancellation prevents work',async()=>{const box=outbox();await box.createIntent();let reviewed=0;const p=createRelationshipPublicationPipeline({cohort_id:'synthetic',producer_id:'reviewer',outbox:box,loadExtracted:async()=>({}),createReview:async()=>({reviewCandidates:async()=>{reviewed++}}),publisher:{publish:async()=>({}),retrievePage:async()=>({})}});assert.equal((await p.process({run})).status,'held');assert.equal(reviewed,0);const c=AbortSignal.abort();await assert.rejects(p.process({run},{signal:c}),{code:'relationship_pipeline_cancelled'});});
test('explicit candidate-only resume reuses immutable input, preserves intent, and publishes once',async()=>{const box=outbox();await box.createIntent();let loads=0,reviews=0,publishes=0;const p=createRelationshipPublicationPipeline({cohort_id:'synthetic',producer_id:'reviewer',outbox:box,loadExtracted:async()=>{loads++;return{saved:true}},createReview:async()=>({reviewCandidates:async input=>{reviews++;assert.deepEqual(input,{saved:true});return{schema:'resolution-review-receipt-v1',artifact_ref}}}),publisher:{async publish(){publishes++;return{run,producer_id:'reviewer',artifact_ref}},retrievePage:async()=>({})}});const result=await p.process({run},{recoveryOnly:true,resumeCandidateOnly:true});assert.equal(result.status,'complete');assert.deepEqual({loads,reviews,publishes},{loads:1,reviews:1,publishes:1});assert.equal((await box.get()).state,'published');});
test('candidate-only resume is exclusive and a failed review leaves the immutable intent intact',async()=>{const box=outbox();await box.createIntent();let release,started;const waiting=new Promise(resolve=>{release=resolve}),entered=new Promise(resolve=>{started=resolve});const p=createRelationshipPublicationPipeline({cohort_id:'synthetic',producer_id:'reviewer',outbox:box,loadExtracted:async()=>({}),createReview:async()=>({reviewCandidates:async()=>{started();await waiting;return{schema:'resolution-review-receipt-v1',artifact_ref}}}),publisher:{async publish(){return{run,producer_id:'reviewer',artifact_ref}},retrievePage:async()=>({})}});const first=p.process({run},{recoveryOnly:true,resumeCandidateOnly:true});await entered;const second=await p.process({run},{recoveryOnly:true,resumeCandidateOnly:true});assert.equal(second.code,'relationship_review_in_progress');release();assert.equal((await first).status,'complete');const failed=outbox();await failed.createIntent();const failure=createRelationshipPublicationPipeline({cohort_id:'synthetic',producer_id:'reviewer',outbox:failed,loadExtracted:async()=>({}),createReview:async()=>{throw Error('review failed')},publisher:{publish:async()=>assert.fail('must not publish'),retrievePage:async()=>({})}});assert.equal((await failure.process({run},{recoveryOnly:true,resumeCandidateOnly:true})).status,'held');assert.equal((await failed.get()).state,'intent_only');});
test('paused review is preserved and recovery emits bounded page monitor metadata',async()=>{const box=outbox();let monitors=[];const p=createRelationshipPublicationPipeline({cohort_id:'synthetic',producer_id:'reviewer',outbox:box,loadExtracted:async()=>({}),createReview:async()=>({reviewCandidates:async()=>{throw Object.assign(Error('paused'),{code:'subscription_review_incomplete',review_status:'paused'})}}),publisher:{publish:async()=>({}),retrievePage:async()=>({})},onMonitor:async m=>monitors.push(m)});assert.equal((await p.process({run})).status,'paused');assert.equal((await p.process({run})).status,'held');assert.equal((await p.recover({limit:1})).monitor.schema,'relationship-publication-monitor-v1');assert.equal(monitors.length,1);assert.equal(monitors[0].scope,'page');assert.ok(monitors[0].scanned_nodes>=0);});
