import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { materializeTaskInputs, proofFromResult, run, validateHandoff, validatePorts } from "./identity-registry-exporter-task.mjs";
const sourcePrefix="graph-trial/20260912/identity-registry/cfo-pilot/source",snapshotPrefix="graph-trial/20260912/identity-registry/cfo-pilot/snapshots";
const storage={bucket:"otchealth-finance-legal-dr-55c84f6b",prefix:sourcePrefix,region:"us-east-1",sse:{algorithm:"AES256"},approved_policy_canonical_sha256:"a".repeat(64),approved_storage_scope_sha256:"b".repeat(64)};
const handoff={schema:"cfo-xero-organisation-explicit-export-handoff-v1",source:{key:"graph-trial/20260912/identity-registry/cfo-pilot/source/identity-registries/xero-organisation/c".repeat(0)+"graph-trial/20260912/identity-registry/cfo-pilot/source/identity-registries/xero-organisation/"+"c".repeat(64)+".json",version_id:"version-1",sha256:"c".repeat(64),storage},export_input:{registry_id:"cfo-registry",prefix:"graph-trial/20260912/identity-registry/cfo-pilot/snapshots"}};
const ports={schema:"cfo-identity-registry-explicit-export-ports-v1",kms:{key_id:"arn:aws:kms:us-east-1:900915535335:key/11111111-2222-3333-4444-555555555555",region:"us-east-1"},source_storage:{...storage,prefix:snapshotPrefix}};
test("task materializes the CFO-owned handoff and exact public ports to private create-only files",()=>{const dir=mkdtempSync(join(tmpdir(),"identity-registry-task-test-"));try{const paths=materializeTaskInputs({handoffJson:JSON.stringify(handoff),portsJson:JSON.stringify(ports),dir});assert.deepEqual(JSON.parse(readFileSync(paths.handoffPath,"utf8")).source,handoff.source);assert.deepEqual(JSON.parse(readFileSync(paths.portsPath,"utf8")).kms,ports.kms);}finally{rmSync(dir,{recursive:true,force:true});}});
test("task loader rejects record-bearing handoffs and a forged storage boundary",()=>{assert.throws(()=>materializeTaskInputs({handoffJson:JSON.stringify({...handoff,export_input:{records:[]}}),portsJson:JSON.stringify(ports)}),{code:"identity_registry_exporter_handoff_invalid"});assert.throws(()=>validateHandoff({...handoff,source:{...handoff.source,storage:{...storage,prefix:snapshotPrefix}}}),{code:"identity_registry_exporter_handoff_invalid"});assert.throws(()=>validatePorts({...ports,source_storage:{records:[]}}),{code:"identity_registry_exporter_ports_invalid"});});
function result(){const pin={key:`${snapshotPrefix}/identity-registries/cfo/manifest.json`,version_id:"version-1",sha256:"d".repeat(64)};return {schema:"cfo-xero-organisation-explicit-export-result-v1",public_config:{},receipt:{schema:"source-identity-registry-explicit-export-receipt-v1",registry_id:"cfo-registry",manifest_version:"manifest-1",source_generation:"generation-1",page_count:1,coverage_binding_count:1,coverage_binding_sha256:"e".repeat(64),shard_count:1,public_key_sha256:"f".repeat(64),manifest:pin,pointer:{...pin,key:`${snapshotPrefix}/identity-registries/cfo/pointer.json`}}};}
test("task proof contains only fixed-prefix immutable output pins",()=>{const published=result();assert.deepEqual(proofFromResult(published).manifest,published.receipt.manifest);assert.throws(()=>proofFromResult({...published,receipt:{...published.receipt,manifest:{...published.receipt.manifest,key:"graph-trial/elsewhere/manifest.json"}}}),{code:"identity_registry_exporter_task_result_invalid"});});
test("task invokes only the fixed source runner and emits a receipt-only proof",()=>{let runner,argv;const published=result();const output=run({env:{CFO_IDENTITY_REGISTRY_HANDOFF_JSON:JSON.stringify(handoff),CFO_IDENTITY_REGISTRY_PORTS_JSON:JSON.stringify(ports)},spawn:(command,args)=>{runner=command;argv=args;writeFileSync(args[args.indexOf("--output")+1],JSON.stringify(published));return {status:0,stdout:"",stderr:""};}});assert.equal(runner,process.execPath);assert.deepEqual(argv.slice(0,2),["tools/xero-organisation-explicit-export-run.mjs","--handoff"]);assert.deepEqual(Object.keys(output.immutable_output_proof).sort(),["coverage_binding_count","coverage_binding_sha256","manifest","manifest_version","page_count","pointer","public_key_sha256","registry_id","shard_count","source_generation"].sort());});
test("gateway image copies the fixed exporter and source-handoff runners with every runtime module",()=>{const docker=readFileSync(new URL("../Dockerfile",import.meta.url),"utf8");for(const file of ["identity-registry-exporter-task.mjs","xero-organisation-explicit-export-run.mjs","identity-registry-explicit-export.mjs","identity-registry-explicit-export-ports.mjs","xero-organisation-source-export-run.mjs","xero-organisation-source-handoff-run.mjs"]){assert.equal(docker.includes(`/app/tools/${file}`),true);assert.equal(docker.includes(`tools/${file}`),true);}});
