import assert from 'node:assert/strict';
import test from 'node:test';
import { handoffProofFromResult, parseCli, runXeroOrganisationSourceHandoff } from './xero-organisation-source-handoff-run.mjs';

const storage={bucket:'otchealth-finance-legal-dr-55c84f6b',prefix:'graph-trial/20260912/identity-registry/cfo-pilot/source',region:'us-east-1',approvedPolicyCanonicalSha256:'a'.repeat(64),approvedStorageScopeSha256:'b'.repeat(64),operationTimeoutMs:1000,sse:{algorithm:'AES256'}};
const deployment={schema:'cfo-xero-organisation-source-handoff-deployment-v1',source_deployment:{schema:'cfo-xero-organisation-source-deployment-v1',deployment:{org:'otchealth',source_storage:storage}}};
test('accepts only exact absolute deployment and output arguments',()=>{assert.deepEqual(parseCli(['--deployment','C:\\source.json','--output','C:\\result.json']),{deployment:'C:\\source.json',output:'C:\\result.json'});assert.equal(parseCli(['--deployment','source.json','--output','C:\\result.json']),null);});
test('publishes source handoff through the source-owner storage writer and returns no record values',async()=>{let published,written;const result=await runXeroOrganisationSourceHandoff({argv:['--deployment','C:\\source.json','--output','C:\\result.json'],read:async()=>JSON.stringify(deployment),persist:async input=>{assert.deepEqual(input,deployment.source_deployment.deployment);return {record:{source_document_version:'version-1',source_sha256:'b'.repeat(64)},receipt:{raw_response_persisted:false,company_only_gate:true}};},storeFactory:input=>({storage:input}),publish:async input=>{published=input;return {key:'graph-trial/20260912/identity-registry/cfo-pilot/source/identity-registries/xero-organisation/handoffs/x.json',version_id:'version-2',sha256:'c'.repeat(64)};},write:async (_path,value,options)=>{written={value,options};}});assert.deepEqual(result,{output_written:true,handoff:{key:'graph-trial/20260912/identity-registry/cfo-pilot/source/identity-registries/xero-organisation/handoffs/x.json',version_id:'version-2',sha256:'c'.repeat(64)}});assert.deepEqual(published.sourceStorage,storage);assert.deepEqual(published.writer.storage,storage);assert.equal(published.exportInput.registry_id,"cfo-identity-registry-pilot");assert.equal(published.exportInput.catalog.catalog_sha256,"b".repeat(64));assert.equal(published.exportInput.records,undefined);assert.equal(written.options.mode,0o600);assert.equal(written.value.includes('source_document_version'),false);assert.equal(written.value.includes('source_sha256'),false);});
test('rejects a record-bearing handoff deployment before calling Xero',async()=>{await assert.rejects(runXeroOrganisationSourceHandoff({argv:['--deployment','C:\\source.json','--output','C:\\result.json'],read:async()=>JSON.stringify({...deployment,records:[]}),persist:async()=>{throw Error('must not run');},storeFactory:()=>{throw Error('must not run');},publish:async()=>{throw Error('must not run');},write:async()=>{throw Error('must not run');}}),{code:'xero_organisation_handoff_deployment_invalid'});});

test('emits only a validated immutable handoff proof to the launcher boundary',()=>{const result={schema:'cfo-xero-organisation-source-handoff-result-v1',handoff:{key:'graph-trial/20260912/identity-registry/cfo-pilot/source/identity-registries/xero-organisation/handoffs/x.json',version_id:'version-2',sha256:'c'.repeat(64)},source_receipt:{company_only_gate:true}};assert.deepEqual(handoffProofFromResult(result),result.handoff);assert.throws(()=>handoffProofFromResult({...result,handoff:{...result.handoff,key:'graph-trial/elsewhere/x.json'}}),{code:'xero_organisation_handoff_result_invalid'});});
